const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
module.exports=async({page,base})=>{
 const h=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../data/history/execution-history.json'))),investments=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../data/budget/2027/investments.json')));
 const ready=()=>page.waitForFunction(()=>document.querySelector('#content')?.getAttribute('aria-busy')==='false');
 for(const width of [1440,390,320]){
  await page.setViewportSize({width,height:1100});
  await page.goto(base+'#proyecto-2027?vista=compare');await ready();assert(page.url().includes('vista=summary'));assert.equal(await page.locator('.tabs [data-project-tab]').count(),4);assert.equal(await page.locator('.explorer-location').count(),0);
  assert.equal(await page.locator('.fiscal-flow-panel').count(),1);assert.equal(await page.locator('.fiscal-result-card').count(),4);assert(await page.locator('.fiscal-flow-panel').isVisible());assert((await page.locator('.flow-financing').innerText()).includes('918.357.557.463'));
  await page.locator('.fiscal-result-card.is-final').click();await page.locator('#reading-detail-dialog[open]').waitFor();assert((await page.locator('#reading-detail-body').innerText()).includes('1.316.442.866'));await page.keyboard.press('Escape');
  await page.goto(base+'#evolucion?periodo=2026-2&serie=capital');await ready();assert.equal(await page.locator('#execution-series').inputValue(),'capital');assert.equal(await page.locator('[data-execution-year]').count(),31);await page.locator('#execution-year').selectOption('2027');assert((await page.locator('#execution-point').innerText()).includes('3.459.982.968.167'));await page.reload();await ready();assert.equal(await page.locator('#execution-series').inputValue(),'capital');
  for(const [series,ceiling] of [['total','20'],['currentPrimary','16'],['capital','4']]){await page.locator('#execution-series').selectOption(series);await ready();assert.equal(await page.locator('.execution-chart>text').nth(4).textContent(),ceiling);}
  await page.goto(base+'#comparar');await ready();assert.equal(await page.locator('.pair-panel').evaluate(e=>e.tagName),'SECTION');assert.equal(await page.locator('.pair-sheet>.pair-metrics>div').count(),6);assert((await page.locator('.pair-panel').innerText()).includes('2024'));assert.equal(await page.locator('.province-history-chart path').count(),5);assert((await page.locator('.province-history-chart').getAttribute('aria-label')).includes('250'));
  await page.goto(base+'#inicio');await ready();assert((await page.locator('.hero-person').innerText()).includes('Presupuesto por porteño, por año'));assert(!(await page.locator('.hero-person').innerText()).includes('Censo'));await page.locator('[data-per-capita-guide]').click();await ready();assert(page.url().includes('tema=por-habitante'));assert((await page.locator('.per-capita-guide').innerText()).includes('3.121.707'));assert((await page.locator('.per-capita-guide').innerText()).includes('No es una factura'));
  await page.goto(base+'#presupuesto-explicado?tema=por-habitante');await ready();assert.equal(await page.locator('.per-capita-guide').count(),1);
  await page.goto(base+'#proyecto-2027?vista=revenue');await ready();assert.equal(await page.locator('.treemap-branch').count(),1);assert((await page.locator('.treemap-branch').innerText()).includes('55,1%'));await page.locator('.treemap-branch-interior [data-reading-detail]').filter({hasText:'Ingresos Brutos'}).click();await page.locator('#reading-detail-dialog[open]').waitFor();assert((await page.locator('#reading-detail-body').innerText()).includes('13.279.892.329.152'));await page.locator('#reading-detail-body [data-method-section]').click();await ready();assert(page.url().includes('#metodologia'));assert.equal(await page.locator('#reading-detail-dialog[open]').count(),0);
  for(const period of ['2025-4','2026-2']){await page.goto(base+'#explorar?periodo='+period);await ready();assert.equal(await page.locator('.fiscal-flow-svg').count(),1);assert(await page.locator('.fiscal-result-card.is-final').isVisible());assert((await page.locator('.fiscal-flow-svg').getAttribute('aria-label')).includes(period==='2025-4'?'281.525.677.404':'917.460.104.312'));if(width<600){assert(await page.locator('.fiscal-flow-mobile').isVisible());assert(await page.locator('.flow-mobile-labels button').filter({hasText:'Intereses'}).isVisible());assert(!await page.locator('.fiscal-flow-scroll').isVisible());}}
  await page.goto(base+'#gastos?periodo=2025-4');await ready();assert(await page.locator('.annual-visible-changes .change-chart').isVisible());await page.goto(base+'#gastos?periodo=2026-2');await ready();assert(await page.locator('.semester-analysis .change-chart .change-row').first().isVisible());
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 }
 for(const project of investments.projects){assert(project.displayName);for(let i=0;i<3;i++)assert.equal(project.components.reduce((sum,c)=>sum+c.amounts[i],0),project.amounts[i]);}
 const lineF=investments.projects.find(r=>r.name.includes('LINEA F'));assert(lineF.displayName.includes('Ingeniería y Arquitectura'));assert.equal(lineF.components.length,2);
 assert.equal(h.series.capital.rows.length,31);
 if(process.env.QA_SCREENSHOTS){const out=path.resolve(process.env.QA_SCREENSHOTS);for(const [name,route,selector,width] of [['caif-2027','#proyecto-2027?vista=summary','.fiscal-flow-panel',1440],['caif-2026-mobile','#explorar?periodo=2026-2','.fiscal-flow-panel',390],['ingresos-2027','#proyecto-2027?vista=revenue','.treemap-figure',1440],['comparacion-nueva','#comparar','.pair-panel',1440]]){await page.setViewportSize({width,height:1600});await page.goto(base+route);await ready();await page.evaluate(()=>document.fonts.ready);await page.locator(selector).scrollIntoViewIfNeeded();await page.locator(selector).screenshot({path:path.join(out,name+'.png'),animations:'disabled'});}}
 console.log('Octubre: CAIF visible, desglose navegable, capital, cinco provincias, empleo y obras verificadas en tres anchos.');
};
