const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright');
const base=process.env.SITE_URL||'http://127.0.0.1:8766/Presupuesto-CABA/';
const routes=['#inicio','#proyecto-2027?vista=summary','#proyecto-2027?vista=expenses','#proyecto-2027?vista=revenue','#proyecto-2027?vista=compare','#explorar?periodo=2026-2','#gastos?periodo=2026-2','#explorar?periodo=2025-4','#gastos?periodo=2025-4','#ingresos?periodo=2026-2','#evolucion?periodo=2026-2','#comparar','#comparar?universo=world','#estructura?periodo=2026-2','#sueldos?periodo=2026-2','#presupuesto-explicado','#metodologia?seccion=presupuesto-2027'];
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});
 const errors=[],failed=[],checks=[];const page=await browser.newPage();
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(new URL(r.url()).origin===new URL(base).origin&&r.status()>=400)failed.push(r.status()+' '+r.url());});
 for(const width of [1440,390,320])for(const route of routes){
  await page.setViewportSize({width,height:1000});await page.goto(base+route);
  await page.waitForFunction(()=>document.querySelector('#content')?.getAttribute('aria-busy')==='false');
  await page.evaluate(()=>document.fonts.ready);
  assert(!await page.getByText('No pudimos cargar esta vista.').count());assert(await page.locator('#content').innerText());
  if(route==='#inicio')assert((await page.locator('.hero-data').innerText()).includes('19.877.152.039.294'));
  if(route==='#inicio'){assert.equal(await page.locator('.main-nav button').count(),4);assert(await page.locator('.hero-request-value').evaluate(e=>e.scrollWidth<=e.clientWidth+1));const text=await page.locator('.hero-data').innerText();assert(text.includes('24.094.340.599.263')&&text.includes('7.718.322'));assert.equal(await page.locator('.approved-teaser,.edition').count(),0);}
  if(route.startsWith('#proyecto')){assert((await page.locator('.project-page').innerText()).includes('Proyecto de Presupuesto 2027'));assert.equal(await page.locator('.tabs [data-view="salaries"],.tabs [data-view="structure"]').count(),0);assert(!await page.locator('.tabs').innerText().then(t=>t.includes('tributarios')));}
  if(route==='#proyecto-2027?vista=compare'){assert((await page.locator('.project-comparison-result').innerText()).includes('+2,7%'));assert.equal(await page.locator('#project-compare-prices').inputValue(),'real');}
  if(route.startsWith('#sueldos')){assert(page.url().includes('#estructura'));assert.equal(await page.locator('.government-conduction').count(),1);}
  if(route.startsWith('#comparar')){assert(page.url().includes('universo=argentina'));assert.equal(await page.locator('.national-layout .justice-note,.compare-universes,.world-comparison').count(),0);assert(!(await page.locator('#province-detail').innerText()).includes('Diferencia con CABA'));}
  if(route.startsWith('#estructura')){assert.equal(await page.locator('.government-count>strong').innerText(),'2.595');assert.deepEqual(await page.locator('.conduction-grid article>strong').allTextContents(),['10','18','82','344','932','855']);assert.equal(await page.locator('.government-directory .treemap-access,.government-branches').count(),0);}
  if(route.startsWith('#evolucion')){assert.equal(await page.locator('#execution-year option').count(),31);assert.equal(await page.locator('.project-history-marker').count(),1);assert.equal(await page.locator('.project-history-bridge').getAttribute('stroke-dasharray'),'3 5');assert((await page.locator('.history-exception').innerText()).includes('Ajuste de precios estimado'));}
  const percentageErrors=await page.evaluate(()=>{const bad=[];for(const e of document.querySelectorAll('#content *')){const values=[...e.childNodes].filter(n=>n.nodeType===3).map(n=>n.textContent);for(const a of ['title','aria-label','data-viz-tip'])if(e.hasAttribute(a))values.push(e.getAttribute(a));for(const v of values)for(const m of v.matchAll(/([−+\-]?)(\d+(?:\.\d{3})*),(\d+)\s*%/g))if(Number(m[2].replaceAll('.',''))>=10||m[3].length!==1)bad.push(m[0]);}return [...new Set(bad)];});assert.deepEqual(percentageErrors,[],route+' percentages');
  assert.equal(await page.locator('[data-view="salaries"]:visible,[data-universe="world"]:visible,.salary-latest,.salary-hierarchy').count(),0);assert.equal(await page.locator('a[href*="salary"],a[href*="salaries"],a[href*="sueldo-funcionarios"],a[href*="comparisons-world"],a[href*="seccion=mundo"],a[href*="seccion=sueldos"]').count(),0);{const text=await page.locator('#content').textContent();const match=text.match(/.{0,120}(?:sueldo|salarial|ciudades del mundo|CABA en el mundo|comparaciones internacionales).{0,180}/i);assert(!match,route+' '+width+': '+match?.[0]);}assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),width+" "+route+": "+JSON.stringify(await page.evaluate(()=>Array.from(document.querySelectorAll("body *")).filter(e=>e.clientWidth>0&&e.scrollWidth>e.clientWidth+2&&getComputedStyle(e).display!=="none").slice(0,20).map(e=>[e.tagName,e.className,e.clientWidth,e.scrollWidth,e.innerText?.slice(0,120),getComputedStyle(e).overflowX]))));checks.push(width+' '+route);
 }
 // Fiscal map: two independent bases, progressive hierarchy and reloadable selection.
 for(const width of [1440,768,390,360]){
  await page.setViewportSize({width,height:1000});await page.goto(base+'#inicio');await page.waitForFunction(()=>document.querySelector('#content')?.getAttribute('aria-busy')==='false'&&document.querySelector('.fiscal-map')&&document.querySelector('[data-fm-reading="amount"]')?.getAttribute('aria-pressed')==='true');
  await page.locator('[data-fm-expand="rec_tributos_propios"]').click();await page.locator('[data-fm-select="tax_iibb"]').click();await page.waitForFunction(()=>document.querySelector('#fm-context .fm-detail')?.textContent.includes('55%'));await page.locator('#fm-context .fm-detail').waitFor({state:'visible'});assert((await page.locator('#fm-context').innerText()).includes('55%'),`IIBB detail at ${width}px`);assert((await page.locator('#fm-context').innerText()).includes('13.279.892.329.152'));
  await page.locator('[data-fm-expand="fin_social"]').click();await page.locator('[data-fm-select="fun_educ"]').click();assert((await page.locator('#fm-context').innerText()).includes('20%'));assert.equal(await page.locator('#fm-children-rec_tributos_propios').getAttribute('hidden'),null);
  await page.locator('[data-fm-reading="hundred"]').click();assert((await page.locator('[data-fm-select="tax_iibb"]').innerText()).includes('55,1'));await page.reload();await page.waitForFunction(()=>document.querySelector('[data-fm-reading="hundred"]')?.getAttribute('aria-pressed')==='true');await page.locator('#fm-context').scrollIntoViewIfNeeded();await page.locator('#fm-context .fm-detail').waitFor({state:'visible'});assert((await page.locator('#fm-context').innerText()).includes('Educación'));assert.equal(await page.locator('[data-fm-expand="fin_social"]').getAttribute('aria-expanded'),'true');
  for(const view of ['who','object','economic','purpose']){await page.locator(`[data-fm-view="${view}"]`).click();assert.equal(await page.locator(`[data-fm-view="${view}"]`).getAttribute('aria-pressed'),'true');assert(await page.locator('.fm-spend .fm-root').count());}
  if(width===1440){await page.waitForFunction(()=>document.querySelectorAll('.fm-ribbons path').length===12);assert.equal(await page.locator('.fm-ribbons path').count(),12);}
  if(width<850)assert.equal(await page.locator('.fm-ribbons').evaluate(e=>getComputedStyle(e).display),'none');
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.goto(base+'#proyecto-2027?vista=summary');await page.waitForFunction(()=>document.querySelector('#content')?.getAttribute('aria-busy')==='false'&&document.querySelector('.fiscal-result-card.is-final'));await page.locator('.fiscal-result-card.is-final').click();assert.equal(await page.locator('#reading-detail-dialog').evaluate(e=>e.open),true);assert((await page.locator('#reading-detail-body').innerText()).includes('1.316.442.866'));await page.keyboard.press('Escape');assert.equal(await page.locator('#reading-detail-dialog').evaluate(e=>e.open),false);
  await page.locator('#obras-2027>summary').click();await page.locator('#investment-search').fill('LINEA F');await page.waitForFunction(()=>document.querySelectorAll('.investment-row').length===1);await page.locator('.investment-row').click();assert((await page.locator('.investment-years').innerText()).includes('368.930.498.582'));assert(await page.locator('#project-detail-dialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await page.keyboard.press('Escape');
 }
 await page.goto(base+'#proyecto-2027?vista=compare&base=initial&precios=nominal');await page.waitForFunction(()=>document.querySelector('#project-compare-base')?.value==='initial');assert((await page.locator('.project-comparison-result').innerText()).includes('+39%'));await page.reload();await page.waitForFunction(()=>document.querySelector('#project-compare-base')?.value==='initial');
 if(process.env.QA_SCREENSHOTS){const out=path.resolve(process.env.QA_SCREENSHOTS);fs.mkdirSync(out,{recursive:true});for(const width of [1366,390]){const capture=await browser.newPage({viewport:{width,height:1000}});await capture.goto(base+'#inicio');await capture.waitForFunction(()=>document.querySelector('#content')?.getAttribute('aria-busy')==='false'&&document.querySelector('.fiscal-map'));await capture.evaluate(()=>document.fonts.ready);await capture.locator('.fiscal-map').screenshot({path:path.join(out,`mapa-${width}.png`)});await capture.close();}}
 await page.goto(base+'#proyecto-2027?vista=expenses');await page.waitForFunction(()=>document.querySelector('#content')?.getAttribute('aria-busy')==='false');await page.locator('.purpose-rest [data-project-purpose]').first().click();await page.waitForFunction(()=>document.querySelector('.project-controls [data-project-reset]'));assert(new URL(page.url()).hash.includes('finalidad='));await page.reload();await page.waitForFunction(()=>document.querySelector('.project-controls [data-project-reset]'));
 await page.locator('[data-project-reset]').click();await page.waitForFunction(()=>!document.querySelector('.project-controls [data-project-reset]'));await page.locator('#project-dimension').selectOption('objects');await page.waitForFunction(()=>document.querySelector('.project-values caption')?.textContent.includes('8 categorías'));await page.locator('.exact-values summary').first().click();assert((await page.locator('.project-values').first().innerText()).includes('Personal'));
 await page.locator('.main-nav [data-view="summary"]').click();await page.waitForFunction(()=>document.querySelector('.area-search'));if(await page.locator('#mobile-period').isVisible())await page.locator('#mobile-period').selectOption('2026-2');else await page.locator('[data-period="2026-2"]').click();await page.waitForFunction(()=>document.querySelector('.fiscal-summary'));assert(page.url().includes('#explorar?periodo=2026-2'));
 await page.goto(base+'#proyecto-2027?vista=revenue&apertura=taxRevenue');await page.waitForFunction(()=>document.querySelector('#project-revenue-mode')?.value==='taxRevenue');assert.equal(await page.locator('.project-values tbody tr').count(),4);
 await page.goto(base+'#proyecto-2027?vista=compare&apertura=objects');await page.waitForFunction(()=>document.querySelector('#project-compare-dimension')?.value==='objects');assert.equal(await page.locator('.stage-comparison table tbody tr').count(),8);
 await page.locator('#project-compare-prices').selectOption('nominal');await page.waitForFunction(()=>document.querySelector('.project-comparison-result')?.textContent.includes('+21%'));await page.reload();await page.waitForFunction(()=>document.querySelector('#project-compare-prices')?.value==='nominal');assert(page.url().includes('precios=nominal'));

 await page.goto(base+'#proyecto-2027?vista=compare');await page.waitForFunction(()=>document.querySelector('.change-chart'));await page.locator('[data-project-change-mode="amount"]').click();await page.waitForFunction(()=>document.querySelector('.change-chart figcaption')?.textContent.includes('billones'));await page.reload();await page.waitForFunction(()=>document.querySelector('[data-project-change-mode="amount"]')?.getAttribute('aria-pressed')==='true');
 await page.locator('.change-row').first().scrollIntoViewIfNeeded();await page.locator('.change-row').first().focus();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>{window.scrollBy(0,12);requestAnimationFrame(resolve)})));assert.equal(await page.locator('#viz-tooltip').getAttribute('aria-hidden'),'false');await page.keyboard.press('Escape');assert.equal(await page.locator('#viz-tooltip').getAttribute('aria-hidden'),'true');
 await page.goto(base+'#evolucion?periodo=2026-2');await page.waitForFunction(()=>document.querySelector('#execution-year'));await page.locator('#execution-year').selectOption('2027');assert((await page.locator('#execution-point').innerText()).includes('24.094.340.599.263'));await page.locator('[data-execution-year="2027"]').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#viz-tooltip').getAttribute('aria-hidden'),'false');
 await page.goto(base+'#explorar?periodo=2025-4');await page.waitForFunction(()=>document.querySelector('.fiscal-summary'));assert.equal(await page.locator('.tabs button:visible').count(),3);assert((await page.locator('.tabs').innerText()).includes('Gasto ejecutado'));
 await page.goto(base+'#metodologia?seccion=historia');await page.waitForFunction(()=>document.querySelector('#metodo-historia')?.textContent.includes('Esta vista estima precios promedio anuales'));
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto(base+'#inicio');await page.waitForFunction(()=>document.querySelector('.hero-data'));assert.equal(await page.locator('.hero-request').evaluate(e=>getComputedStyle(e).animationName),'none');await page.emulateMedia({reducedMotion:'no-preference'});
 await page.goto(base+'#metodologia?seccion=presupuesto-2027');await page.waitForFunction(()=>document.querySelector('#metodo-presupuesto-2027'));assert(page.url().includes('seccion=presupuesto-2027'));
 await page.goto(base+'#metodologia?seccion=provincias');await page.waitForFunction(()=>document.querySelector('#metodo-provincias .justice-note'));assert.equal(await page.locator('.method-index a').count(),8);
 await page.goto(base+'#detalle?periodo=2025-4&dimension=7&filtros=%7B%226%22%3A%223%22%7D');await page.reload();await page.waitForFunction(()=>document.querySelector('#content')?.getAttribute('aria-busy')==='false');
 assert(page.url().includes('dimension=7'));assert(!await page.getByText('No pudimos cargar esta vista.').count());
 await page.goto(base+'#estructura?periodo=2026-2');await page.waitForFunction(()=>document.querySelector('.conduction-grid'));await page.locator('[data-conduction-list="ministers"]').click();assert.equal(await page.locator('#conduction-lists').getAttribute('open'),'');assert.equal(await page.locator('#conduction-lists .conduction-people').first().locator('li').count(),10);if(await page.locator('.government-directory [data-treemap-rest]').count()){await page.locator('.government-directory [data-treemap-rest]').click();await page.waitForFunction(()=>document.querySelector('.government-directory .rest-detail'));await page.locator('.government-directory .rest-list [data-government-node]').first().click();}else await page.locator('.government-directory .treemap-tile[data-government-node]').first().click();await page.waitForFunction(()=>!document.querySelector('.government-conduction'));assert(/nodo=[1-9]/.test(page.url()));await page.reload();await page.waitForFunction(()=>document.querySelector('.government-directory'));assert.equal(await page.locator('.government-conduction').count(),0);
 await page.goto(base+'#comparar');await page.waitForFunction(()=>document.querySelector('#province-select'));await page.locator('#province-select').selectOption('06');assert((await page.locator('#province-detail').innerText()).includes('Buenos Aires'));assert((await page.locator('#province-detail').innerText()).includes('frente a CABA'));await page.locator('[data-compare-pair]').click();assert.equal(await page.locator('#province-pair>.pair-panel').evaluate(e=>e.tagName),'SECTION');await page.locator('.comparison-extra>summary').click();await page.locator('#arg-history-indicator').selectOption('balance');await page.waitForFunction(()=>document.querySelector('#arg-history-indicator')?.value==='balance'&&document.querySelector('.comparison-extra')?.open);await page.locator('#arg-indicator').selectOption('employeesRate');await page.waitForFunction(()=>document.querySelector('#arg-indicator')?.value==='employeesRate');await page.locator('[data-compare-display="ranking"]').click();await page.waitForFunction(()=>document.querySelector('.national-ranking'));await page.locator('#real-history-basis').selectOption('perCapita');await page.waitForFunction(()=>document.querySelector('#real-history-basis')?.value==='perCapita');
 await require('./citizen-reading.cjs')({page,browser,base});
 await require('./area-reports-reading.cjs')({page,base});
 await require('./government-areas-reading.cjs')({page,base});
 await require('./government-areas-all-reading.cjs')({page,base});
 await require('./visual-polish-reading.cjs')({page,base});
 await require('./october-reading.cjs')({page,base});
 await require('./audit-reading.cjs')({page,base});
 await require('./composition-reading.cjs')(page,base);
 const catalog=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../data/index.json')));
 for(const d of catalog.datasets)for(const file of d.files){const response=await page.request.get(new URL(file,base).href);assert.equal(response.status(),200,file);}
 for(const file of fs.readdirSync(path.resolve(__dirname,'../public/sources'))){const response=await page.request.get(new URL('sources/'+file,base).href);assert.equal(response.status(),200,file);}
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);console.log(JSON.stringify({smoke:checks.length,deepLinkReload:true,datasets:catalog.datasets.length,downloads:true,errors}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
