'use strict';
// Presentation and loading are separate from the existing aggregation engine.
const dataRequests=new Map();let renderSequence=0;
const featureEnabled=name=>state.config.flags?.[name]!==false;
function applyVisibility(){if(!featureEnabled('salaries')&&state.view==='salaries'){state.view='structure';state.period=state.config.currentExecutionPeriod;state.structureMode='people';state.governmentNode=0;}if(!featureEnabled('world')){state.compareUniverse='argentina';delete state.worldCity;delete state.worldBasis;delete state.worldCurrency;}}
const pageFor=view=>['landing','compare','method','explained'].includes(view)?view:'explore';
const summaryFor=period=>state.manifest.periods.find(p=>`${p.year}-${p.quarter}`===period);
const periodName=p=>state.config.periodLabels?.[`${p.year}-${p.quarter}`]||(p.quarter===4?`Cierre ${p.year}`:`Avance ${p.year}`);
const cutDate=p=>`${['31/03','30/06','30/09','31/12'][p.quarter-1]}/${p.year}`;
function latestAdvance(){const closed=state.manifest.periods.filter(p=>p.quarter===4),last=Math.max(...closed.map(p=>p.year));return state.manifest.periods.filter(p=>p.year>last).sort((a,b)=>b.year-a.year||b.quarter-a.quarter)[0]}
const basePrice=()=>state.manifest.base.replace('Promedio ','promedio ');
function provenance(kind,text){const labels={official:'DATO OFICIAL',calculation:'CÁLCULO PROPIO',analysis:'LECTURA / ANÁLISIS LLA'};return `<details class="provenance ${kind}"><summary>${labels[kind]} <span aria-hidden="true">ⓘ</span></summary><p>${text}</p></details>`}
// Curated future readings require explicit verification and a supporting source.
// An empty catalogue produces no citizen-facing placeholder.
function renderInsights(){const items=(state.config.insights||[]).filter(i=>i.verified===true&&i.published===true&&['official','calculation','analysis'].includes(i.kind)&&i.title&&i.text&&/^https:\/\//.test(i.source));return items.length?`<section class="home-section"><h2>Claves del presupuesto</h2>${items.map(i=>`<article class="budget-reading"><h3>${E(i.title)}</h3><p>${E(i.text)}</p>${provenance(i.kind,`${E(i.method||'')} <a href="${E(i.source)}" target="_blank" rel="noopener">Ver respaldo</a>`)}</article>`).join('')}</section>`:''}
async function dataFile(name){if(!dataRequests.has(name))dataRequests.set(name,fetch(`${Site.url('data/'+name+'.json')}?v=${document.querySelector('meta[name="site-build"]')?.getAttribute('content')||'local'}`).then(r=>{if(!r.ok)throw Error(`No se pudo cargar ${name}`);return r.json()}).catch(e=>{dataRequests.delete(name);throw e}));return dataRequests.get(name)}
async function ensureViewData(view,period){const work=[];
  if(['project','landing','history','method'].includes(view)&&state.config.featuredBudgetFile)work.push(Site.load(state.config.featuredBudgetFile).then(d=>state.project=d));
  if(['project','method'].includes(view)&&state.config.projectComparisonFile)work.push(Site.load(state.config.projectComparisonFile).then(d=>state.projectComparison=d));
  if(['project','method'].includes(view)&&state.config.featuredBudgetFile)work.push(dataFile('fiscal-map-2027').then(d=>state.fiscalMap=d),dataFile('stages-2027').then(d=>state.projectStages=d),dataFile('investments-2027').then(d=>state.projectInvestments=d),dataFile('companions-2027').then(d=>state.projectCompanions=d));
  if(view==='landing')work.push(dataFile('caif').then(d=>state.caif=d));
  if(view==='home')work.push(dataFile('approved-vs-executed').then(d=>state.approvedExecution=d));
  if(view==='history'||view==='method'&&state.methodSection==='historia')work.push(dataFile('execution-history').then(d=>state.executionHistory=d));
  if(view==='structure')work.push(dataFile('government-directory').then(d=>state.governmentDirectory=d),dataFile('conduction').then(d=>state.conduction=d),dataFile('conduction-counts').then(d=>state.conductionCounts=d));
  if(view==='method')work.push(dataFile('rem-benchmark-2026').then(d=>state.remBenchmark=d));
  if(view==='method'&&state.methodSection==='provincias')work.push(dataFile('comparisons-argentina').then(d=>state.comparisons=d));
  if(['home','detail','structure'].includes(view))work.push(dataFile('organigram').then(d=>state.organigram=d));
  if(['home','income'].includes(view)&&period==='2025-4')work.push(dataFile('annual-comparison').then(d=>state.annualComparison=d));
  if(['history','compare'].includes(view))work.push(dataFile('population-annual').then(d=>state.annualPopulation=d));
  if(view==='history')work.push(dataFile('category-history').then(d=>state.categoryHistory=d));
  if(view==='salaries')work.push(dataFile('conduction').then(d=>state.conduction=d));
  if(view==='salaries')work.push(dataFile('salary-hierarchy').then(d=>state.salaryHierarchy=d));
  if(['home','detail','financial','structure'].includes(view))work.push(dataFile(period).then(d=>{cache[period]=d}));
  if(view==='income'&&state.config.incomePeriods.includes(period)){const p=period;work.push(dataFile(`income-${p}`).then(d=>{state.incomes??={};state.incomes[p]=d}));}
  if(view==='income'&&state.config.incomeAnalysisPeriods?.[period])work.push(dataFile(state.config.incomeAnalysisPeriods[period]).then(d=>state.incomeComparison=d));
  if(view==='history')work.push(dataFile('budget-history-long').then(d=>state.longBudget=d),dataFile('inflation-long').then(d=>state.longInflation=d),dataFile('budget-history-usd').then(d=>state.historyUSD=d));
  if(view==='compare')work.push(dataFile('national-spending-history').then(d=>state.nationalSpending=d),dataFile('inflation-long').then(d=>state.longInflation=d));
  if(view==='structure')work.push(dataFile('institutional-structure').then(d=>state.institutional=d));
  if(view==='salaries')work.push(dataFile('salaries').then(d=>{state.salaries=d;state.salaryMonth??=d.rows.map(r=>[r.year,r.month]).sort((a,b)=>b[0]-a[0]||b[1]-a[1])[0].join('-')}),dataFile('salary-latest-reference').then(d=>state.salaryReference=d));
  if(view==='structure'&&state.config.employmentFile)work.push(dataFile(state.config.employmentFile).then(d=>state.employment=d));
  if(view==='compare'){work.push(dataFile('comparisons-argentina').then(d=>state.comparisons=d),dataFile('province-paths').then(d=>state.provincePaths=d));if(featureEnabled('world')&&state.config.worldComparisonFile)work.push(dataFile(state.config.worldComparisonFile).then(d=>state.world=d));}
  if(view==='home'&&state.config.analysisPeriods[period])work.push(dataFile(state.config.analysisPeriods[period]).then(d=>state.semesterAnalysis=d));
  if(view==='summary'&&state.config.caifFile)work.push(dataFile(state.config.caifFile).then(d=>state.caif=d));
  await Promise.all(work);
}
function landing(){if(state.config.featuredBudgetFile)return projectLanding();const p=state.currentBudget,v=p.budget,d=p.executed,H=state.content.home,T=text=>Site.text(text,{year:p.year,cutDate:cutDate(p),population:fmt(p.population)});
const questions=H.questions.items;
return `<div class="citizen-home"><section class="intro"><div><p class="eyebrow">${E(H.hero.eyebrow)}</p><h1>${E(H.hero.title)}<span>.</span></h1><p class="intro-copy">${E(H.hero.description)}</p><button class="primary-btn" data-view="summary" data-snapshot="${state.config.currentExecutionPeriod}">${E(H.hero.action)} <span aria-hidden="true">↗</span></button></div><aside class="intro-aside"><span class="city-rule"></span><p>${H.hero.aside}</p><small>${H.hero.source}</small></aside></section>

<section class="home-section panorama" aria-labelledby="panorama-title"><div class="section-intro"><p class="eyebrow">${E(T(H.panorama.eyebrow))}</p><h2 id="panorama-title">${E(H.panorama.title)}</h2></div><div class="panorama-grid"><article><p>${E(T(H.panorama.budgetLabel))}</p><strong>${money(v)}</strong><span>${E(H.panorama.budgetDescription)}</span>${provenance('official',H.panorama.budgetNote)}<button class="text-link" data-view="home" data-snapshot="${state.config.currentExecutionPeriod}">Ver el presupuesto ↗</button></article><article><p>${E(H.panorama.perCapitaLabel)}</p><strong>${money(p.perCapita)}</strong><span>${E(H.panorama.perCapitaDescription)}</span>${provenance('calculation',T(H.panorama.perCapitaNote))}<button class="text-link" data-view="compare" data-snapshot="${state.config.currentExecutionPeriod}" data-current-budget>Comparar por habitante ↗</button></article><article><p>Gasto ejecutado · ${p.quarter===4?'enero–diciembre':'enero–junio'} ${p.year}</p><strong>${money(d)}</strong><span>Gasto ejecutado durante ${p.quarter===4?'el año':'los primeros seis meses'}.</span>${provenance('official',H.panorama.executedNote)}<button class="text-link" data-view="home" data-snapshot="${state.config.currentExecutionPeriod}">Explorar el avance ↗</button></article></div></section>
${homeFiscalReadings()}<section class="home-section" aria-labelledby="questions-title"><div class="section-intro"><p class="eyebrow">${E(H.questions.eyebrow)}</p><h2 id="questions-title">${E(H.questions.title)}</h2></div><div class="question-grid">${questions.map(([n,t,s,view,visual])=>`<button class="question-card" data-view="${view}" data-snapshot="${state.config.currentExecutionPeriod}"><span class="question-number">${n} <span aria-hidden="true">↗</span></span><h3>${t}</h3><p>${s}</p><span class="mini-visual ${visual}" aria-hidden="true">${visual==='line'?'<svg viewBox="0 0 220 50"><path d="M0 44 L35 31 L72 37 L107 15 L140 22 L180 9 L220 2"/></svg>':'<i></i><i></i><i></i><i></i>'}</span></button>`).join('')}</div></section>
${renderInsights()}${state.config.comparisonReady?`<section class="comparison-cta"><div><p class="eyebrow">${E(H.comparison.eyebrow)}</p><h2>${E(H.comparison.title)}</h2><p>${E(H.comparison.description)}</p></div><button class="primary-btn" data-view="compare">Comparar CABA ↗</button></section>`:''}
<div class="edition"><span>Presupuesto al ${cutDate(p)}</span><span>Pesos nominales de ${p.year}</span><span>Actualización: ${state.manifest.updated.split('-').reverse().join('/')}</span><button data-view="method">Ver fuentes y actualización ↗</button></div>
<section class="reading-guide"><h2>${E(H.guide.title)}</h2><p>${E(H.guide.description)}</p><button class="text-link" data-view="explained">Entender el presupuesto en pocos minutos ↗</button></section></div>`;
}
function explorerShell(){const isExplore=pageFor(state.view)==='explore';$('#explorer-controls').hidden=!isExplore;const p=summaryFor(state.period),years=state.manifest.periods.map(p=>p.year);const closed=p.quarter===4;document.querySelector('.tabs [data-view=home]').textContent=closed?'Gasto ejecutado':'Gastos';document.querySelector('.tabs [data-view=income]').textContent=closed?'Ingresos realizados':'Ingresos';document.querySelector('.price-label').textContent=state.view==='history'?'Comparación en términos reales':state.view==='salaries'?'Salarios brutos publicados':`Pesos nominales de ${p.year}`;$('#period-tabs').innerHTML=state.config.featuredPeriods.slice().sort((a,b)=>b.localeCompare(a)).map(id=>{const p=summaryFor(id);return `<button data-period="${id}" class="${state.period===id&&state.view!=='history'?'active':''}">${periodName(p)}</button>`}).join('')+`<button data-view="history" class="${state.view==='history'?'active':''}">Evolución 1997–${Math.max(...years)}</button>`;document.querySelectorAll('.main-nav [data-view]').forEach(b=>{const active=(b.dataset.view==='summary'?'explore':b.dataset.view)===pageFor(state.view);b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});document.querySelectorAll('.tabs [data-view]').forEach(b=>{const active=b.dataset.view==='home'?['home','detail','financial'].includes(state.view):b.dataset.view===state.view;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});$('#search').disabled=!cache[state.period];$('.search-label').hidden=$('.search-box').hidden=(!(['home','detail','financial'].includes(state.view)||state.view==='structure'&&state.structureMode==='budget'));$('#compare-nav').hidden=!state.config.comparisonReady;$('#updated-label').textContent=state.view==='compare'?`Comparaciones: actualización ${state.comparisons?.updated?.split('-').reverse().join('/')||'11/09/2026'}`:`Datos presupuestarios actualizados: ${state.manifest.updated.split('-').reverse().join('/')}`;}
async function renderExperience(){applyVisibility();const token=++renderSequence,view=state.view,period=state.period;const openDetails=state.navigationRequested?[]:[...document.querySelectorAll('#content details[open]')].map(d=>d.querySelector(':scope > summary')?.textContent);const content=$('#content'),active=document.activeElement,focusId=active?.id,focusAttr=['data-zero','data-salary-range','data-compare-display','data-universe','data-world-currency','data-world-basis','data-project-change-mode','data-history-change-mode'].map(k=>[k,active?.getAttribute?.(k)]).find(([,v])=>v&&/^[a-zA-Z0-9-]+$/.test(v));content.setAttribute('aria-busy','true');explorerShell();try{await ensureViewData(view,period);if(token!==renderSequence)return;state.dataset=cache[period]||summaryFor(period);const views={landing,home,detail,financial,method,...extraViews};treemapViews.clear();let markup=(views[view]||landing)();if(!markup.includes('<h1'))markup=markup.replace(/<h2([^>]*)>([\s\S]*?)<\/h2>/,'<h1$1>$2</h1>');content.innerHTML=Site.markup(polishMarkup(citizenLanguage(markup,view),view));content.setAttribute('aria-busy','false');for(const d of content.querySelectorAll('details'))if(openDetails.includes(d.querySelector(':scope > summary')?.textContent))d.open=true;decorateTables();enhanceVisuals(view);explorerShell();syncRoute();if(state.navigationRequested){state.navigationRequested=false;content.focus({preventScroll:true});if(view==='landing')window.scrollTo({top:0,behavior:'instant'});else content.scrollIntoView({block:'start',behavior:'instant'});}else if(focusId){document.getElementById(focusId)?.focus({preventScroll:true});}else if(focusAttr){document.querySelector(`[${focusAttr[0]}="${focusAttr[1]}"]`)?.focus({preventScroll:true});}}catch(e){if(token!==renderSequence)return;content.innerHTML='<section class="panel"><h2>No pudimos cargar esta vista.</h2><p>Reintentá la carga para consultar los datos.</p><button class="primary-btn" data-retry>Reintentar</button></section>';content.setAttribute('aria-busy','false');console.error(e)}}
document.addEventListener('click',e=>{if(e.target.closest('[data-retry]'))render()});
document.addEventListener('click',e=>{if(e.target.closest('[data-view],[data-period],[data-dim],[data-group],[data-select-dim],[data-structure-path],[data-breadcrumb],[data-income]')){state.navigationRequested=true;$('#search-results').hidden=true;$('#search').value='';$('#clear-search').hidden=true;}},true);
window.appReady=Site.ready.then(async()=>{const [manifest,current,population,fx]=await Promise.all([dataFile('manifest'),Site.load(Site.config.currentBudgetFile),dataFile('population-caba'),dataFile('fx-caba')]);state.manifest=manifest;state.config={...Site.config,population,fx};state.currentBudget=current;state.content=Site.content;state.period=state.config.defaultPeriod;state.view='landing';state.dataset=summaryFor(state.period);document.querySelector('.main-nav [data-snapshot]').dataset.snapshot=state.config.currentExecutionPeriod;readRoute();return render()}).catch(e=>{$('#content').innerHTML='<p>No se pudieron cargar las fuentes. Recargá la página para reintentar.</p>';console.error(e)});

const routeNames={landing:'inicio',summary:'explorar',home:'gastos',structure:'estructura',income:'ingresos',salaries:'sueldos',history:'evolucion',explained:'presupuesto-explicado',method:'metodologia',compare:'comparar',detail:'detalle',financial:'aplicaciones-financieras'};
function syncRoute(){const q=new URLSearchParams();if(pageFor(state.view)==='explore')q.set('periodo',state.period);if(state.view==='detail'){q.set('dimension',String(state.dim));if(Object.keys(state.filters).length)q.set('filtros',JSON.stringify(state.filters));if(state.exclude)q.set('excluir',state.exclude)}if(state.view==='structure'){q.set('estructura',state.structureMode||'people');if(state.governmentNode)q.set('nodo',String(state.governmentNode));}if(state.view==='structure'&&state.structureMode==='institutional'&&state.orgNode)q.set('organismo',state.orgNode);if(state.view==='structure'&&state.structurePath?.length)q.set('ruta',JSON.stringify(state.structurePath));if(state.view==='income'&&state.incomePath?.length)q.set('rubro',state.incomePath.join('.'));if(state.view==='compare'){for(const [param,key] of Object.entries({universo:'compareUniverse',corte:'comparePeriod',indicador:'compareIndicator',vista:'compareDisplay',provincia:'selectedProvince',ciudad:'worldCity',base:'worldBasis',moneda:'worldCurrency'}))if(state[key])q.set(param,state[key]);}const hash='#'+(routeNames[state.view]||'inicio')+(q.size?'?'+q:'');if(window.location.hash!==hash)window.history.pushState(null,'',hash)}
function readRoute(){const [slug,query='']=window.location.hash.slice(1).split('?'),view=Object.entries(routeNames).find(([,s])=>s===slug)?.[0];if(!view)return;const q=new URLSearchParams(query),period=q.get('periodo');state.view=view;if(view==='compare'){const allowed={universo:['compareUniverse',/^(argentina|world)$/],corte:['comparePeriod',/^\d{4}-[1-4]$/],indicador:['compareIndicator',/^[a-zA-Z]+$/],vista:['compareDisplay',/^(map|ranking)$/],provincia:['selectedProvince',/^\d{2}$/],ciudad:['worldCity',/^[a-z]+$/],base:['worldBasis',/^(perCapita|total)$/],moneda:['worldCurrency',/^(official|ppa)$/]};for(const [param,[key,pattern]] of Object.entries(allowed)){const value=q.get(param);state[key]=value&&pattern.test(value)?value:undefined;}}state.filters={};state.exclude=null;state.structurePath=[];state.incomePath=[];if(view==='income'){const rubro=q.get('rubro');if(rubro&&/^[12](?:\.\d+){0,4}$/.test(rubro))state.incomePath=rubro.split('.')}if(period&&summaryFor(period))state.period=period;state.metric=state.period.endsWith('-4')?'d':'v';if(view==='detail'){const dim=Number(q.get('dimension'));state.dim=Number.isInteger(dim)&&dim>=0&&dim<=9?dim:1;try{const filters=JSON.parse(q.get('filtros')||'{}');state.filters=Object.fromEntries(Object.entries(filters).filter(([d,v])=>/^\d$/.test(d)&&typeof v==='string'&&/^(\d+|judicial)$/.test(v)));const exclude=q.get('excluir');if(exclude&&/^[\d,]+$/.test(exclude))state.exclude=exclude}catch{state.filters={}}}if(view==='structure'){const org=q.get('organismo');if(org&&/^org-[a-f0-9]{14}$/.test(org)){state.orgNode=org;state.structureMode='institutional'}else{state.orgNode=null;state.structureMode=['people','budget','institutional'].includes(q.get('estructura'))?q.get('estructura'):q.has('ruta')?'budget':'people'}state.governmentNode=/^\d{1,5}$/.test(q.get('nodo')||'')?Number(q.get('nodo')):0;try{const path=JSON.parse(q.get('ruta')||'[]');if(Array.isArray(path)&&path.length<=4&&path.every(v=>typeof v==='string'&&/^\d+$/.test(v)))state.structurePath=path}catch{state.structurePath=[]}}}
window.addEventListener('popstate',()=>{readRoute();state.navigationRequested=true;render()});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);const responsiveViews=['summary','home','detail','income','history','salaries','compare'];if(responsiveViews.includes(state.view))resizeTimer=setTimeout(()=>{if(responsiveViews.includes(state.view))render();},180)});

function citizenLanguage(markup,view){
 return markup.split(/(<[^>]*>)/).map(part=>part.startsWith('<')?part:part
 .replace(/Gastos realizados/g,'Gastos ejecutados').replace(/gastos realizados/g,'gastos ejecutados')
 .replace(/Gasto realizado/g,'Gasto ejecutado').replace(/gasto realizado/g,'gasto ejecutado')
 .replace(/Gasto devengado/g,'Gasto ejecutado')
 .replace(/\$ constantes|Pesos constantes/g,text=>view==='method'?text:'Valores actualizados por inflación')
 .replace(/a precios constantes/g,text=>view==='method'?text:'con valores actualizados por inflación')
 .replace(/remuneración ordinaria/gi,'salario bruto').replace(/sueldo(?: bruto)? ordinario/gi,'salario bruto')
 .replace(/Ordinario nominal/g,'Salario bruto nominal').replace(/Ordinario real/g,'Salario bruto real')
 .replace(/\$\s*-?\d{1,3}(?:\.\d{3})+,\d+/g,amount=>money(Number(amount.replace(/\$|\s|\./g,'').replace(',','.'))))
 ).join('');
}
