'use strict';

function longBudgetPoint(r){return `<strong>${r.year} · ${E(r.status)}</strong> — ${money(r.real)} · pesos del 2.º trimestre de 2026. <a href="${E(r.source)}" target="_blank" rel="noopener">Ver fuente</a>`}
function longInflationNote(){const d=state.longInflation;return d?`<details><summary>Cómo descontamos la inflación en esta serie</summary><p>${E(d.method)}</p><p>El tramo anterior a mayo de 2016 procede del archivo aportado «${E(d.localFile)}». No es una serie nacional oficial homogénea: el archivo no detalla las provincias ni sus ponderaciones. Desde diciembre de 2016 se utilizan los niveles originales del IPC nacional.</p><p><a href="${E(d.officialSource)}" target="_blank" rel="noopener">INDEC · serie nacional original</a> · <a href="/data/inflation-long.json" download>Ver el empalme, índices y celdas de origen</a></p></details>`:''}
function longBudgetPanel(){const data=state.longBudget;if(!data)return '';const rows=data.rows,last=rows.at(-1),chosen=rows.find(r=>r.year===state.budgetYear)||last;return `<div class="chart-panel"><div class="page-heading"><div><h2>El presupuesto, de 2005 a ${last.year}</h2><p class="chart-unit">Billones de pesos del 2.º trimestre de 2026 · inflación descontada con IPC empalmado</p></div><a class="small-btn" href="/data/budget-history-long.csv" download>↓ Descargar serie</a></div><div class="comparison-legend"><span><i style="background:#ba882c"></i>Aprobado · 2005–2012</span><span><i style="background:#67339b"></i>Definitivo · 2013–2025</span><span><i style="background:#ab80c9"></i>Actualizado a junio · 2026</span></div>${longBudgetChart()}<label class="observation-picker">Consultar un año<select id="budget-observation">${rows.slice().reverse().map(r=>`<option value="v-${r.year}" ${r.year===chosen.year?'selected':''}>${r.year} · ${E(r.status)}</option>`).join('')}</select></label><p id="budget-point" class="point-readout" aria-live="polite">${longBudgetPoint(chosen)}</p><p class="note">Cada punto representa el presupuesto de todo un año. Para 2026 se utiliza un índice anual proyectado con expectativas anteriores a la aprobación; los años cerrados usan inflación observada. Hasta 2012 se muestra el aprobado; desde 2013, el actualizado al cierre. El punto de 2026 incluye cambios hasta el 30 de junio. 1 billón = $1.000.000.000.000.</p><details><summary>Ver los ${rows.length} presupuestos y sus fuentes</summary><div class="table-wrap"><table><caption>Presupuesto anual · gastos corrientes y de capital</caption><thead><tr><th>Año</th><th>Presupuesto</th><th>Pesos originales</th><th>Pesos del 2T 2026</th><th>Fuente</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.year}</td><td>${E(r.status)}</td><td class="num">${money(r.nominal)}</td><td class="num">${money(r.real)}</td><td><a href="${E(r.source)}" target="_blank" rel="noopener">${E(r.reference)}</a><small class="office">${E(r.note)}</small></td></tr>`).join('')}</tbody></table></div><p>${data.notes.map(E).join(' ')}</p></details>${budgetBenchmarkNote()}${longInflationNote()}</div>`}
function longBudgetChart(){const rows=state.longBudget?.rows;if(!rows?.length)return '';const W=chartWidth(),H=350,L=42,R=16,T=65,B=46,low=Math.min(...rows.map(r=>r.real))/1e12,high=Math.max(...rows.map(r=>r.real))/1e12,scale=niceScale(Math.max(0,low-(high-low)*.12),high+(high-low)*.12),min=scale.min,max=scale.max,x=i=>L+i/(rows.length-1)*(W-L-R),y=v=>H-B-(v/1e12-min)/(max-min)*(H-T-B),colors={approved:'#ba882c',final:'#67339b',advance:'#ab80c9'};const bands=[{a:0,b:7.5,name:'2005–2012',sub:'APROBADO',color:'#ba882c'},{a:7.5,b:20.5,name:'2013–2025',sub:'DEFINITIVO',color:'#67339b'},{a:20.5,b:21,name:'2026',sub:'VIGENTE A JUNIO',color:'#ab80c9'}];return `<div class="line-chart"><svg viewBox="0 0 ${W} ${H}" role="group" aria-label="Presupuesto anual desde 2005, escala ${state.historyZero?'desde cero':'ajustada'}"><title>Presupuestos a precios del segundo trimestre de 2026; 2026 utiliza expectativas anteriores a su sanción</title>${bands.map((b,i)=>`<rect x="${x(b.a)}" y="${T}" width="${Math.max(1,x(b.b)-x(b.a))}" height="${H-B-T}" fill="${b.color}" opacity=".075"/>${i?`<line x1="${x(b.a)}" x2="${x(b.a)}" y1="${T}" y2="${H-B}" stroke="${b.color}" stroke-dasharray="3 4"/>`:''}<text x="${i===2?W-R:(x(b.a)+x(b.b))/2}" y="${i===2?48:18}" text-anchor="${i===2?'end':'middle'}" style="font-size:${W<450?10:12}px;font-weight:700">${i===2?`${b.name} · ${b.sub}`:`<tspan x="${(x(b.a)+x(b.b))/2}">${b.name}</tspan><tspan x="${(x(b.a)+x(b.b))/2}" dy="13">${b.sub}</tspan>`}</text>`).join('')}${scale.ticks.map(n=>{return `<line x1="${L}" x2="${W-R}" y1="${y(n*1e12)}" y2="${y(n*1e12)}" stroke="#e8e1f0"/><text x="${L-8}" y="${y(n*1e12)+4}" text-anchor="end">${naturalTick(n)}</text>`}).join('')}${rows.slice(1).map((r,i)=>`<path data-budget-series="${r.kind}" d="M${x(i)},${y(rows[i].real)} L${x(i+1)},${y(r.real)}" fill="none" stroke="${colors[r.kind]}" stroke-width="3" ${r.kind==='advance'||r.kind!==rows[i].kind?'stroke-dasharray="5 5"':''}/>`).join('')}${rows.map((r,i)=>`<circle data-budget-point="v-${r.year}" tabindex="-1" role="button" aria-label="${r.year}: ${money(r.real)}, ${E(r.status)}" cx="${x(i)}" cy="${y(r.real)}" r="${r.kind==='advance'?5.5:3.5}" stroke="white" stroke-width="1.5" fill="${colors[r.kind]}"><title>${r.year} · ${E(r.status)}: ${money(r.real)}</title></circle>${annualTick(i,rows.length,W,r.year)?`<text x="${x(i)}" y="${H-18}" text-anchor="${i===0?'start':i===rows.length-1?'end':'middle'}">${r.year}</text>`:''}`).join('')}</svg></div>`}

function budgetEvolutionChart(){return longBudgetChart()}

const mayorInfo={
  mauricio:{name:'Mauricio Macri',dates:'Dic. 2007 – dic. 2015',start:'2007-12',end:'2015-12',color:'#aa8c00',image:'mauricio-macri',crop:'320 10 490 540',width:1920,height:1079},
  larreta:{name:'Horacio Rodríguez Larreta',dates:'Dic. 2015 – dic. 2023',start:'2015-12',end:'2023-12',color:'#a97900',image:'horacio-larreta',crop:'120 55 350 390',width:628,height:628},
  jorge:{name:'Jorge Macri',dates:'Desde diciembre de 2023',start:'2023-12',end:'2026-07',color:'#9c7800',image:'jorge-macri',crop:'220 10 285 320',width:788,height:591}
};
const dateOrdinal=date=>{const[y,m]=date.split('-').map(Number);return y*12+m-1};
function salaryDate(date){const[y,m]=date.split('-').map(Number);return `${state.salaries.months[m-1]} ${y}`}
function mayorPortrait(id){const m=mayorInfo[id];return `<svg viewBox="${m.crop}" aria-hidden="true"><image href="/assets/${m.image}.png" width="${m.width}" height="${m.height}"/></svg>`}
function salaryHistoryRows(){return (state.salaryHistory?.rows||[]).filter(r=>r.mayor==='jorge')}
function salaryHistoryPanel(){const data=state.salaryHistory;if(!data)return '';state.salaryHistoryMetric='assignment';state.salaryRange='jorge';const records=salaryHistoryRows(),last=records.at(-1),basis=salaryDate(data.realBasis.month);return `<section class="salary-history chart-panel" aria-labelledby="salary-history-title"><p class="eyebrow">JORGE MACRI · DESDE DICIEMBRE DE 2023</p><h3 id="salary-history-title">Cómo evolucionó el sueldo</h3><div class="salary-highlights"><div><span>Último salario bruto publicado · ${salaryDate(last.date)}</span><strong>${money(last.assignment)}</strong></div></div>${presidentComparison(last)}<p class="chart-unit">Pesos de ${basis} · inflación descontada</p>${salaryEvolutionChart(records)}<div class="comparison-legend"><span><i style="background:#8a6700"></i>Salario bruto real</span><span>◆ Adicional por aguinaldo</span></div><label class="observation-picker">Consultar un mes<select id="salary-observation">${records.slice().reverse().map(r=>`<option value="${r.date}|jorge">${salaryDate(r.date)}${r.bonus?' · aguinaldo':''}</option>`).join('')}</select></label><div class="salary-point" id="salary-point" aria-live="polite">${salaryObservation(last)}</div> <details><summary>Datos, fórmula y fuentes de la serie</summary><p>La línea descuenta la inflación con el IPCBA mensual. Fórmula: asignación nominal × ${fmt(data.realBasis.index,2)} / IPCBA del mes. Base: ${basis}, último mes con sueldo publicado. El último sueldo coincide en pesos nominales y reales. El círculo vacío identifica la liquidación parcial de diciembre de 2023.</p><p>Los segmentos con rombo agregan el aguinaldo al salario bruto sin aguinaldo, ambos a los mismos precios. La tabla conserva además los importes nominales publicados. No son sueldos netos.</p><p><a href="${E(data.realBasis.source)}" target="_blank" rel="noopener">IPCBA · fuente</a> · <a href="/data/salary-jorge-macri.csv" download>Descargar serie y factores</a> · <a href="/data/salary-history.json" download>Metadatos y referencias</a></p><div class="table-wrap"><table><caption>Jorge Macri · importes brutos; base real ${basis}</caption><thead><tr><th>Mes</th><th>Salario bruto nominal sin aguinaldo</th><th>Aguinaldo nominal</th><th>Total bruto nominal</th><th>Salario bruto real</th><th>Fuente</th></tr></thead><tbody>${records.slice().reverse().map(r=>`<tr><td>${salaryDate(r.date)}${r.partial?' · parcial':''}</td><td class="num">${money(r.assignment)}</td><td class="num">${r.bonus?money(r.bonus):'—'}</td><td class="num">${money(r.gross)}</td><td class="num">${money(r.ordinaryReal)}</td><td>${salarySource(r)}</td></tr>`).join('')}</tbody></table></div></details></section>`;}
function salarySource(r){return `<a href="${E(state.salaryHistory.sources.find(s=>s.year===r.sourceYear).url)}" target="_blank" rel="noopener">GCBA · ${r.sourceYear}, fila ${r.sourceRow}</a>`}
function presidentComparison(r){const p=state.salaryHistory.presidentReference;if(!p||r.date<'2026-01')return '';return `<p class="president-equivalence">${r.bonus?`El aguinaldo de este mes equivale a <b>${fmt(r.bonus/p.value,2)} sueldos brutos mensuales ordinarios del Presidente de la Nación.</b>`:`Equivale a <b>${fmt(r.assignment/p.value,2)} veces el sueldo bruto mensual del Presidente de la Nación.</b>`}</p><details><summary>Referencia presidencial y alcance</summary><p>Referencia ordinaria: ${money(p.value)} nominales, publicada en el <a href="${p.source}" target="_blank" rel="noopener">Informe 142 al Congreso</a>. El <a href="${p.freezeSource}" target="_blank" rel="noopener">Decreto 931/2025, artículos 2 y 3</a>, publicado el 02/01/2026, excluye al Presidente y al Vicepresidente de las recomposiciones. Consulta: 14/09/2026.</p><p>Se compara remuneración ordinaria nominal con la referencia ordinaria nominal. La equivalencia del aguinaldo es de magnitudes distintas expresamente identificadas. No se verificó el SAC presidencial del mismo mes, por lo que no se compara total contra total.</p></details>`}
function salaryObservation(r){return `<span>${salaryDate(r.date)}${r.partial?' · liquidación parcial':''}: <b>${money(r.ordinaryReal)} de salario bruto real</b>${r.bonus?` + ${money(r.grossReal-r.ordinaryReal)} de aguinaldo real`:''}. Base ${salaryDate(state.salaryHistory.realBasis.month)}.</span><details><summary>Ver importe publicado y fuente</summary><p>Salario bruto nominal sin aguinaldo: ${money(r.assignment)}.${r.bonus?` Aguinaldo nominal: ${money(r.bonus)}. Total bruto: ${money(r.gross)}.`:''}</p>${salarySource(r)}</details>`}

function salaryEvolutionChart(records){const W=chartWidth(),H=400,L=91,R=18,T=74,B=44,min=9e6,max=Math.max(20e6,Math.ceil(Math.max(...records.map(r=>r.grossReal))/1e6)*1e6),start=dateOrdinal(records[0].date),end=dateOrdinal(records.at(-1).date),x=r=>L+(dateOrdinal(r.date)-start)/(end-start)*(W-L-R),y=v=>H-B-(v-min)/(max-min)*(H-T-B);let open=false;const path=records.map((r,i)=>{if(r.partial){open=false;return ''}const cmd=open&&dateOrdinal(r.date)-dateOrdinal(records[i-1].date)===1?'L':'M';open=true;return `${cmd}${x(r)},${y(r.ordinaryReal)}`}).join(' '),ticks=[9e6,...niceScale(10e6,max,6,{floor:10e6}).ticks.filter(n=>n<=max)];
 return `<p class="chart-scale">Escala: ${money(min)} a ${money(max)} · base ${salaryDate(state.salaryHistory.realBasis.month)}</p><div class="line-chart salary-line"><svg viewBox="0 0 ${W} ${H}" role="group" aria-label="Salario bruto real de Jorge Macri; los rombos y segmentos adicionales identifican el aguinaldo"><defs><clipPath id="jorge-face"><circle r="25"/></clipPath></defs><g transform="translate(${(L+W-R)/2} 29)"><circle r="27" fill="white" stroke="#9c7800" stroke-width="2"/><g clip-path="url(#jorge-face)"><svg x="-25" y="-25" width="50" height="50" viewBox="${mayorInfo.jorge.crop}"><image href="/assets/jorge-macri.png" width="788" height="591"/></svg></g></g>
 ${ticks.map(n=>`<line x1="${L}" x2="${W-R}" y1="${y(n)}" y2="${y(n)}" stroke="#e7e2d6"/><text x="${L-8}" y="${y(n)+4}" text-anchor="end">${fmt(n)}</text>`).join('')}<path d="${path}" fill="none" stroke="#9c7800" stroke-width="3"/>
 ${records.map((r,i)=>`${r.bonus?`<g data-salary-observation="${r.date}|jorge" role="button" tabindex="-1" aria-label="${E(salaryDate(r.date)+': Adicional por aguinaldo real '+money(r.grossReal-r.ordinaryReal)+'; total bruto real '+money(r.grossReal)+'; pesos de julio de 2026')}"><title>Adicional por aguinaldo real: ${money(r.grossReal-r.ordinaryReal)}; total bruto real: ${money(r.grossReal)} · pesos de julio de 2026. Aguinaldo nominal publicado: ${money(r.bonus)}.</title><line x1="${x(r)}" x2="${x(r)}" y1="${y(r.ordinaryReal)}" y2="${y(r.grossReal)}" stroke="#d4a521" stroke-width="5" opacity=".65"/><path d="M${x(r)} ${y(r.grossReal)-5}l5 5-5 5-5-5Z" fill="#8a6700"/></g>`:''}<circle data-salary-observation="${r.date}|jorge" cx="${x(r)}" cy="${y(r.ordinaryReal)}" r="${r.partial?5:3}" fill="${r.partial?'white':'#9c7800'}" stroke="#9c7800" stroke-width="1.5"><title>${salaryDate(r.date)} · salario bruto real ${money(r.ordinaryReal)} · pesos de julio de 2026. Salario bruto nominal publicado: ${money(r.assignment)}</title></circle>${(i===0||i===records.length-1||i%(W<450?12:5)===0&&i<records.length-3)?`<text x="${x(r)}" y="${H-15}" text-anchor="${i===0?'start':i===records.length-1?'end':'middle'}">${r.date}</text>`:''}`).join('')}</svg></div>`;
}

function signedPct(n){return `${n>0?'+':''}${fmt(n,Math.abs(n)<1?2:1)}%`}
function signedMoney(n){return `${n>0?'+':n<0?'−':''}${short(Math.abs(n))}`}

function semesterAnalysisPanel(){
  const data=state.semesterAnalysis;if(!data)return `<p class="notice">${state.semesterAnalysisFailed?'No se pudo cargar la comparación. Recargá la página para volver a intentar.':'Cargando comparación del primer semestre…'}</p>`;
  const dim=state.analysisDim||'functions',sort=state.analysisSort||'difference';
  const rows=[...data[dim]].sort((a,b)=>sort==='difference'?Math.abs(b.b-b.a)-Math.abs(a.b-a.a):sort==='increase'?(b.b-b.a)-(a.b-a.a):sort==='decrease'?(a.b-a.a)-(b.b-b.a):b.b-a.b);
  const top=rows.slice(0,10),delta=data.fiscal.b-data.fiscal.a;
  const max=Math.max(...rows.map(r=>Math.abs(r.b-r.a)),1),communes=data.communes,maxCom=Math.max(...communes.flatMap(r=>[r.a,r.b]));
  return `<section class="semester-analysis" aria-labelledby="semester-title"><div class="page-heading"><div><p class="eyebrow">PRIMER SEMESTRE · 2025 VS. 2026</p><h2 id="semester-title">Dónde cambió el gasto</h2><p>Gasto ejecutado de enero a junio, descontando la inflación.</p></div><a class="small-btn" href="/data/semester-analysis.csv" download>↓ Descargar análisis</a></div>
  <div class="semester-summary"><div><span>Variación real del gasto fiscal</span><strong>${signedPct((data.fiscal.b/data.fiscal.a-1)*100)}</strong><small>${signedMoney(delta)} respecto del primer semestre de 2025</small></div><div class="semester-totals">${[['2025',data.fiscal.a],['2026',data.fiscal.b]].map(([year,value])=>`<div><b>${year}</b><span class="comparison-track"><i style="width:${value/Math.max(data.fiscal.a,data.fiscal.b)*100}%"></i></span><strong>${short(value)}</strong></div>`).join('')}</div></div>
  <div class="chart-panel"><div class="page-heading"><div><h3>Las variaciones con mayor impacto</h3><p>Compará el cambio porcentual o la diferencia en pesos, descontando la inflación.</p></div></div><div class="tools analysis-tools"><label>Clasificación <select id="analysis-dim"><option value="functions" ${dim==='functions'?'selected':''}>Funciones</option><option value="incisos" ${dim==='incisos'?'selected':''}>Incisos</option><option value="jurisdictions" ${dim==='jurisdictions'?'selected':''}>Jurisdicciones</option></select></label><label>Orden <select id="analysis-sort"><option value="difference" ${sort==='difference'?'selected':''}>Mayor impacto en pesos reales</option><option value="increase" ${sort==='increase'?'selected':''}>Mayores aumentos</option><option value="decrease" ${sort==='decrease'?'selected':''}>Mayores caídas</option><option value="amount" ${sort==='amount'?'selected':''}>Mayor gasto 2026</option></select></label></div>
  ${comparisonToggle(state.historyChangeMode||'percent','data-history-change-mode')}${changeDumbbell(top.map(r=>({...r,name:displayName(r.name)})),{mode:state.historyChangeMode||'percent',reference:'Enero–junio 2025',project:'Enero–junio 2026'})}
  <details><summary>Ver las ${rows.length} ${dim==='functions'?'funciones':dim==='jurisdictions'?'jurisdicciones':'categorías de gasto'} y sus importes</summary>${analysisTable(rows)}</details><p class="note">Se excluyen las aplicaciones financieras. ${dim==='jurisdictions'?'Los cambios de ministerios y competencias pueden alterar la comparación entre jurisdicciones. Se conservan las denominaciones de la planilla, sin forzar equivalencias.':'Un cambio de gasto no permite evaluar, por sí solo, la calidad o los resultados de un servicio.'}</p></div>
  <div class="chart-panel"><div class="page-heading"><div><h3>El gasto de las 15 comunas</h3><p>Comparación del gasto registrado en las unidades de cada comuna.</p></div></div><div class="comparison-legend"><span><i class="year-2025"></i> 1.er semestre 2025</span><span><i class="year-2026"></i> 1.er semestre 2026</span></div><div class="commune-chart">${communes.map(r=>`<div class="commune-row"><strong>${E(r.name)}</strong><div class="paired-bars"><span class="year-2025" style="width:${r.a/maxCom*100}%" title="2025: ${money(r.a)}"></span><span class="year-2026" style="width:${r.b/maxCom*100}%" title="2026: ${money(r.b)}"></span></div><span>${short(r.b)}<small>${r.a?signedPct((r.b/r.a-1)*100):'Sin base'}</small></span></div>`).join('')}</div><p class="note">Importe a la derecha: devengado 2026. Debajo: variación real frente a 2025. Este gasto no representa toda la inversión de la Ciudad en cada territorio.</p><details><summary>Ver importes por comuna</summary>${analysisTable(communes)}</details></div>
  <details class="analysis-method"><summary>Fuente y criterios de esta comparación</summary><p>Fuente: <b>${E(data.sourceFile)}</b>, solapa <b>Análisis</b>. Jurisdicciones: encabezados de las filas 5–79; funciones: 84–107; incisos: 111–118; comunas: 15–29.</p><p>${E(data.method)}</p><p>La exclusión de aplicaciones financieras se cotejó con los códigos económicos de las bases oficiales de ambos semestres. No se suman subtotales con sus componentes.</p><a href="/data/semester-analysis.csv" download>Descargar importes y referencia de cada fila</a></details></section>`;
}
function analysisTable(rows){return `<div class="table-wrap"><table><caption>Devengado · millones de pesos constantes del 2.º trimestre de 2026</caption><thead><tr><th>Concepto</th><th class="num">1S 2025</th><th class="num">1S 2026</th><th class="num">Diferencia</th><th class="num">Variación real</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${E(displayName(r.name))}</td><td class="num">${fmt(r.a/1e6)}</td><td class="num">${fmt(r.b/1e6)}</td><td class="num">${fmt((r.b-r.a)/1e6)}</td><td class="num">${r.a?signedPct((r.b/r.a-1)*100):'Sin base'}</td></tr>`).join('')}</tbody></table></div>`}

document.addEventListener('click',e=>{const b=e.target.closest('[data-salary-range]');if(!b)return;state.salaryRange=b.dataset.salaryRange;state.salaryHistoryMetric=['mauricio','all'].includes(state.salaryRange)?'gross':'assignment';render()});
document.addEventListener('change',e=>{const mapping={'salary-history-metric':'salaryHistoryMetric','analysis-dim':'analysisDim','analysis-sort':'analysisSort'};if(mapping[e.target.id]){state[mapping[e.target.id]]=e.target.value;render()}});
function showSalaryObservation(e){const b=e.target.closest('[data-salary-observation]');if(!b)return;const[date,mayor]=b.dataset.salaryObservation.split('|'),r=state.salaryHistory.rows.find(r=>r.date===date&&r.mayor===mayor);if(r)$('#salary-point').innerHTML=salaryObservation(r,state.salaryHistoryMetric||'assignment')}
document.addEventListener('click',showSalaryObservation);
document.addEventListener('focusin',showSalaryObservation);
document.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){const b=e.target.closest('[data-salary-observation]');if(b){e.preventDefault();showSalaryObservation(e)}}});


function chartWidth(){return Math.max(260,Math.min(1050,(document.querySelector("#content")?.clientWidth||window.innerWidth||1000)-48))}
function showBudgetPoint(e){const b=e.target.closest('[data-budget-point]');if(!b)return;const year=Number(b.dataset.budgetPoint.split('-').at(-1)),r=state.longBudget?.rows.find(r=>r.year===year),out=$('#budget-point');if(out&&r){state.budgetYear=year;out.innerHTML=longBudgetPoint(r);const picker=$('#budget-observation');if(picker)picker.value='v-'+year}}

for(const event of ["click","focusin"])document.addEventListener(event,showBudgetPoint);
document.addEventListener("keydown",e=>{if((e.key==="Enter"||e.key===" ")&&e.target.closest("[data-budget-point]")){e.preventDefault();showBudgetPoint(e)}});

document.addEventListener('change',e=>{if(e.target.id==='salary-observation'){const [date,mayor]=e.target.value.split('|'),r=state.salaryHistory.rows.find(r=>r.date===date&&r.mayor===mayor);if(r)$('#salary-point').innerHTML=salaryObservation(r,state.salaryHistoryMetric||'assignment')}if(e.target.id==='budget-observation')showBudgetPoint({target:{closest:()=>({dataset:{budgetPoint:e.target.value}})}})});

function budgetBenchmarkNote(){const b=state.longBudget?.benchmark2026||state.remBenchmark;if(!b)return '';return `<details class="benchmark-note"><summary>2026: presupuesto medido con las expectativas anteriores a su aprobación</summary><p>El monto nominal es $ 19.877.152.039.294. Para medir la autorización anual se usa el nivel medio de precios proyectado a partir del REM de octubre de 2025, publicado el 7 de noviembre, antes de la sanción del 27 de noviembre. Los años cerrados y las comparaciones de gasto realizado usan inflación observada.</p><p>El 18,7% del REM es diciembre contra diciembre: no se usa como deflactor anual. Con índices conocidos hasta septiembre de 2025 y proyecciones mensuales hasta abril de 2026, se completan mayo–diciembre a una tasa mensual constante de ${fmt(b.completionMonthlyPercent,4)}%, calculada con el dato original de 18,65% (se comunica redondeado a 18,7%). Promedio anual proyectado: ${fmt(b.annualAverage2026,4)} (diciembre de 2016 = 100). La alternativa de interpolación lineal produce ${fmt(b.alternativeAnnualAverages.linear_index,4)}: diferencia de ${fmt(b.alternativeSpreadPercent,2)}%.</p><p>La pregunta es cuánto representa la autorización presupuestaria con las expectativas disponibles al aprobarse. El valor real de 2026 de esta serie es un benchmark ex ante, distinto de una ejecución observada.</p><p><a href="https://www.bcra.gob.ar/archivos/Pdfs/PublicacionesEstadisticas/tablas-relevamiento-expectativas-mercado-oct-2025.xlsx" target="_blank" rel="noopener">Tablas oficiales REM octubre 2025</a> · <a href="/data/rem-benchmark-2026.json" download>Trayectoria mensual, fórmulas y alternativas</a></p></details>`}
document.addEventListener('click',e=>{const b=e.target.closest('[data-zero]');if(b){state.historyZero=b.dataset.zero==='yes';render()}});
