'use strict';
// Fiscal results use the same scope and period for every term of each identity.
function fiscalSummary(){
 const d=state.caif?.periods?.[state.period];if(!d)return `<section class="panel"><h1>Resumen fiscal</h1><p>Este corte no tiene una cuenta ahorro–inversión conciliada en el sitio.</p><button class="primary-btn" data-view="summary" data-snapshot="2026-2">Ver el último semestre disponible</button></section>`;
 const closed=d.quarter===4,metrics=[['Resultado económico primario','economicPrimaryResult','economicPrimaryRatio','de los ingresos corrientes','Ingresos corrientes menos gastos corrientes sin intereses.'],['Resultado primario','primaryResult','primaryRatio','de los ingresos totales','Ingresos totales menos gastos totales sin intereses.'],['Resultado financiero','financialResult','financialRatio','de los ingresos totales','Ingresos totales menos gastos totales, incluidos los intereses.']];
 return `<section class="panel fiscal-summary"><p class="eyebrow">${closed?'CIERRE ANUAL':'ENERO–JUNIO'} · ${d.year}</p><h1>${closed?'Resultado fiscal de '+d.year:'Resultado de los primeros seis meses'}</h1><p class="chart-unit">Pesos nominales · acumulado al ${cutDate(d)}</p><div class="fiscal-kpis">${metrics.map(([name,key,ratio,den,formula])=>`<article class="${d[key]<0?'deficit':'surplus'}"><h2>${name}</h2><p class="result-sign">${d[key]<0?'Déficit':'Superávit'}${closed&&key==='financialResult'?' financiero '+d.year:''}</p><strong>${money(d[key])}</strong><span>${signedPct(d[ratio])} ${den}</span><details><summary>Más información</summary><p>${formula} ${E(state.caif.scope)}</p></details></article>`).join('')}</div>${caifPanel()}${fiscalContext(d)}<div class="fiscal-next"><button class="small-btn" data-view="home">Explorar el gasto ↗</button><button class="small-btn" data-view="income">Explorar los ingresos ↗</button></div></section>`;
}
function caifPanel(){
 const d=state.caif?.periods?.[state.period];if(!d)return '';const steps=[['Ingresos corrientes',0,d.currentIncome,'income'],['Gastos corrientes sin intereses',d.economicPrimaryResult,d.currentIncome,'expense'],['Resultado económico primario',0,d.economicPrimaryResult,'result'],['Ingresos de capital',d.economicPrimaryResult,d.economicPrimaryResult+d.capitalIncome,'income'],['Gastos de capital',d.primaryResult,d.economicPrimaryResult+d.capitalIncome,'expense'],['Resultado primario',0,d.primaryResult,'result'],['Intereses de la deuda',d.financialResult,d.primaryResult,'expense'],['Resultado financiero',0,d.financialResult,'result']],min=Math.min(0,...steps.flatMap(s=>[s[1],s[2]])),max=Math.max(...steps.flatMap(s=>[s[1],s[2]])),span=max-min;
 return `<section class="caif-panel"><h2>De los ingresos al resultado financiero</h2><div class="caif-waterfall" role="group" aria-label="Cuenta ahorro–inversión. Ocho pasos; los tres resultados son subtotales, no importes que se sumen entre sí.">${steps.map(([name,a,b,kind])=>`<div class="waterfall-row"><span>${name}</span><div class="waterfall-track"><i class="waterfall-zero" style="left:${-min/span*100}%"></i><b class="${kind} ${kind==='result'&&b<0?'negative':''}" style="left:${(Math.min(a,b)-min)/span*100}%;width:${Math.max(.12,Math.abs(b-a)/span*100)}%" title="${E(name)}: ${money(kind==='result'?b:Math.abs(b-a))}"></b></div><strong>${short(kind==='result'?b:Math.abs(b-a))}</strong></div>`).join('')}</div><details><summary>Ver detalle de la cuenta ahorro–inversión</summary><div class="table-wrap"><table><caption>Pesos nominales · ${d.quarter===4?'año completo':'enero–junio'} ${d.year}</caption><thead><tr><th>Concepto</th><th>Importe</th></tr></thead><tbody>${[['Ingresos corrientes',d.currentIncome],['Gastos corrientes sin intereses',d.currentPrimaryExpense],['Resultado económico primario',d.economicPrimaryResult],['Ingresos de capital',d.capitalIncome],['Gastos de capital',d.capitalExpense],['Resultado primario',d.primaryResult],['Intereses de la deuda',d.interest],['Resultado financiero',d.financialResult],['Ingresos totales',d.income],['Gastos totales',d.expense]].map(([n,v])=>`<tr><th scope="row">${n}</th><td class="num">${money(v)}</td></tr>`).join('')}</tbody></table></div><p>El resultado económico primario excluye los intereses del gasto corriente. El resultado primario descuenta todos los gastos salvo intereses. El financiero también descuenta los intereses.</p><p>${E(state.caif.scope)} ${E(d.status)}. Los intereses corresponden al código económico 21410000, no a todo el servicio de la deuda.</p><p>${E(d.rounding.method)} Los importes visibles se redondean al peso; los cálculos conservan la precisión original.</p><a href="${E(d.localSource)}" target="_blank" rel="noopener">Informe oficial</a> · <a href="${E(d.interestSource.url)}" target="_blank" rel="noopener">Base detallada de intereses</a> · <a href="/data/caif.json" download>Valores, fórmulas y fuentes</a></details></section>`;
}
function fiscalContext(d){
 const ctx=state.caif.context,rows=d.quarter===2?ctx.semesters:ctx.annual;if(rows.length<2)return `<details class="fiscal-context"><summary>Contexto histórico y cobertura</summary><p>El cierre 2025 está conciliado. Para dibujar una evolución anual faltan otros cierres con ingresos e intereses verificados bajo el mismo alcance.</p><p>${E(ctx.missing)}</p></details>`;
 const series=[{name:'Económico primario / ingresos corrientes',key:'economicPrimaryRatio',color:'#67339b'},{name:'Primario / ingresos totales',key:'primaryRatio',color:'#176872'},{name:'Financiero / ingresos totales',key:'financialRatio',color:'#a15026'}],points=rows.map(r=>({year:r.year,values:series.map(s=>r[s.key])}));
 return `<section class="chart-panel fiscal-context"><h2>Los resultados en perspectiva</h2><p class="chart-unit">Primeros semestres · porcentaje de los ingresos</p><div class="comparison-legend">${series.map(s=>`<span><i style="background:${s.color}"></i>${s.name}</span>`).join('')}</div>${readableLineChart(points,series,{unit:'Porcentaje de los ingresos',index:true})}<details><summary>Datos, fórmulas y cobertura histórica</summary><div class="table-wrap"><table><thead><tr><th>Semestre</th>${series.map(s=>`<th>${s.name}</th>`).join('')}<th>Fuente</th></tr></thead><tbody>${rows.map(r=>`<tr><th>${r.year} · enero–junio</th>${series.map(s=>`<td class="num">${pct(r[s.key])}</td>`).join('')}<td><a href="${r.localSource}" target="_blank" rel="noopener">Informe oficial</a></td></tr>`).join('')}</tbody></table></div><p>${E(ctx.method)}</p><p>${E(ctx.missing)}</p><a href="/data/caif.json" download>Descargar todos los términos y las fuentes</a></details></section>`;
}
Object.assign(extraViews,{summary:fiscalSummary});
function iteration4Method(){return `<details><summary>Los tres resultados fiscales del Resumen</summary><p>Resultado económico primario: ingresos corrientes menos gastos corrientes sin intereses. Su porcentaje se divide por los ingresos corrientes. Resultado primario: ingresos totales menos gastos totales sin intereses. Resultado financiero: ingresos totales menos gastos totales, incluidos los intereses. Los dos últimos porcentajes se dividen por los ingresos totales.</p><p>Intereses: gasto devengado del código económico 21410000. Se excluyen figurativas y financiamiento del universo fiscal. El gráfico histórico compara primeros semestres de 2024, 2025 y 2026. No mezcla esos semestres con el cierre 2025.</p><p>Todos los cálculos conservan los decimales originales. Las cifras monetarias completas de la interfaz se redondean al peso; esa presentación puede producir diferencias de un peso al sumar lo que se ve.</p><a href="/data/caif.json" download>Importes, fórmulas, cobertura y fuentes oficiales</a></details>`}

const treemapViews=new Map();let treemapId=0;
function treemapPlan(all,mobile=false){let n=Math.min(all.length,mobile?8:10),cap=mobile?10:15;while(n<all.length&&n<cap&&all.slice(n).reduce((s,r)=>s+r.value,0)>all[0].value)n++;return n;}
function compositionTreemap(items,{label='Composición del total',formatValue=money,formatShort=short,showKey=true}={}){
 const all=items.filter(r=>Number.isFinite(r.value)&&r.value>0).map(r=>({...r,name:displayName(r.name)})).sort((a,b)=>b.value-a.value),sum=all.reduce((s,r)=>s+r.value,0);if(!sum)return '<p class="notice">No hay importes positivos para representar esta composición.</p>';if(items.some(r=>r.value<0))return '<p class="notice">Hay importes negativos: consultá la tabla para leer la composición sin distorsionar las proporciones.</p>';
 const mobile=window.innerWidth<600,n=treemapPlan(all,mobile),remaining=all.slice(n),id=++treemapId,rows=all.slice(0,n);if(remaining.length)rows.push({name:'Resto',value:remaining.reduce((s,r)=>s+r.value,0),action:`data-treemap-rest="${id}"`,other:true});
 const palette=['#542770','#70408b','#765485','#684474','#805197','#694680','#5b4170','#755987','#664a7b','#725181','#5a3870','#805b90','#65427a','#795187','#604075','#705680'],rects=[];
 function divide(list,x,y,w,h){if(list.length===1){rects.push({...list[0],x,y,w,h});return;}const t=list.reduce((s,r)=>s+r.value,0);let k=1,a=list[0].value;while(k<list.length-1&&Math.abs(a+list[k].value-t/2)<Math.abs(a-t/2))a+=list[k++].value;const ratio=a/t;if(w*(mobile?.9:1.7)>=h){divide(list.slice(0,k),x,y,w*ratio,h);divide(list.slice(k),x+w*ratio,y,w*(1-ratio),h)}else{divide(list.slice(0,k),x,y,w,h*ratio);divide(list.slice(k),x,y+h*ratio,w,h*(1-ratio))}}
 divide(rows.map((r,i)=>({...r,i})),0,0,100,100);const pw=Math.max(248,Math.min(1120,window.innerWidth-100)),ph=mobile?430:350;
 const html=`<figure class="treemap-figure" data-treemap-view="${id}"><figcaption>${E(label)} <span>· 100% del total</span></figcaption><div class="rect-treemap" role="group" aria-label="${E(label)}. El área representa su participación.">${rects.map(r=>{const text=`${r.name}${r.description?' · '+r.description:''}: ${pct(r.value/sum*100)}, ${formatValue(r.value)}${r.other?', abrir '+remaining.length+' categorías':''}`,w=pw*r.w/100,h=ph*r.h/100,small=w<90||h<65||Math.ceil(r.name.length/(w/7))*15+35>h,big=w>145&&h>105;return `<button data-treemap-info="${E(text)}" class="treemap-tile ${small?'tile-no-label':''}" ${r.action||''} style="left:${r.x}%;top:${r.y}%;width:${r.w}%;height:${r.h}%;background:${palette[r.i%palette.length]}" aria-label="${E(text)}" title="${E(text)}">${small?'':`<span class="tile-name">${E(r.name)}</span><strong>${pct(r.value/sum*100)}</strong>${big?`<small class="tile-amount">${formatShort(r.value)}</small>`:''}`}</button>`}).join('')}</div><p class="treemap-readout note" aria-live="polite"></p>${showKey?`<details class="treemap-access"><summary>Ver categorías e importes</summary><ul class="treemap-key">${rows.map(r=>`<li><button class="cell-link" ${r.action||''} data-treemap-info="${E(r.name+': '+formatValue(r.value))}">${E(r.name)} · ${pct(r.value/sum*100)}</button><span>${formatValue(r.value)}</span></li>`).join('')}</ul></details>`:''}</figure>`;
 treemapViews.set(id,{html,remaining,sum,label,formatValue});return html;
}
function treemapRemainder(id){const v=treemapViews.get(id);if(!v)return '';const amount=v.remaining.reduce((s,r)=>s+r.value,0);return `<figure class="treemap-figure rest-detail" data-treemap-view="${id}" tabindex="-1"><figcaption>Detalle de Resto</figcaption><p>${v.remaining.length} categorías que representan ${pct(amount/v.sum*100)} del total</p><button class="small-btn" data-treemap-back="${id}">← Volver a ${E(v.label)}</button><ul class="rest-list">${v.remaining.map(r=>`<li><button class="cell-link" ${r.action||''} data-treemap-info="${E(r.name+': '+v.formatValue(r.value))}">${E(r.name)}</button><span>${v.formatValue(r.value)} <small>${pct(r.value/v.sum*100)}</small></span></li>`).join('')}</ul><p class="treemap-readout note" aria-live="polite"></p></figure>`}
document.addEventListener('click',e=>{const b=e.target.closest('[data-treemap-rest],[data-treemap-back]');if(!b)return;e.stopImmediatePropagation();const id=Number(b.dataset.treemapRest||b.dataset.treemapBack),figure=b.closest('figure');figure.outerHTML=b.dataset.treemapRest?treemapRemainder(id):treemapViews.get(id).html;const next=document.querySelector(`[data-treemap-view="${id}"]`);next.setAttribute('tabindex','-1');next.focus({preventScroll:true});next.scrollIntoView({block:'nearest'})},true);

function salaryHierarchyPanel(){const d=state.salaryHierarchy,c=state.conduction;if(!d||!c)return '';const names={SS:'Subsecretarios',DG:'Directores generales',GO:'Gerentes operativos',SGO:'Subgerentes operativos'};return `<section class="salary-hierarchy chart-panel"><p class="eyebrow">CONDUCCIÓN · CORTE 31/07/2026</p><h2>La estructura de conducción del Gobierno de la Ciudad</h2><div class="hierarchy-levels six-levels">${[['Ministros',c.ministers,'ministers'],['Secretarios',c.secretaries,'secretaries']].map(([name,rows,id])=>`<article><strong class="hierarchy-count">${rows.length}</strong><div><h3>${name}</h3><button class="text-link" data-conduction-list="${id}">Ver listado debajo ↓</button></div></article>`).join('')}${d.levels.map(l=>`<article><strong class="hierarchy-count">${fmt(l.count)}</strong><div><h3>${names[l.id]}</h3><span>Salario bruto mensual de referencia</span><b class="salary-range">Desde ${money(l.salaryMin)}<br>hasta ${money(l.salaryMax)}</b></div></article>`).join('')}</div><details id="conduction-lists"><summary>Ver ministros, secretarios y dependencias</summary>${[['Ministros',c.ministers,'ministers'],['Secretarios',c.secretaries,'secretaries']].map(([name,rows,id])=>`<h3 id="conduction-${id}" tabindex="-1">${name}</h3><div class="table-wrap"><table><thead><tr><th>Responsable publicado</th><th>Área</th><th>Depende de</th></tr></thead><tbody>${rows.map(r=>`<tr><th>${E(displayName(r.name))}</th><td>${E(displayName(r.office))}</td><td>${E(displayName(r.reportsTo))}</td></tr>`).join('')}</tbody></table></div>`).join('')}</details><details><summary>Cómo contamos los cargos y calculamos los salarios</summary><p>${E(c.method)}</p><p>El padrón contiene 12 filas de rango ministro: diez ministerios más Procuración y Sindicatura. Las 20 filas de rango secretario incluyen las 18 secretarías, la Presidencia del Consejo de Derechos de Niñas, Niños y Adolescentes y el Ente de Turismo. Los rangos no equivalen automáticamente a ministerios o secretarías.</p><p>${E(c.deduplication)} ${E(d.method)}</p><p>${E(c.limitation)}</p><p>Salarios de referencia de julio de 2026, sin aguinaldo; no son recibos individuales. La unidad retributiva y las fórmulas conservan todos los decimales en los datos descargables.</p>${d.levels.map(l=>`<p><b>${names[l.id]}:</b> ${E(l.formula)} ${E(l.note)}</p>`).join('')}${d.norms.map(n=>`<p><a href="${E(n.url)}" target="_blank" rel="noopener">${E(n.name)}</a></p>`).join('')}<p><a href="${d.source}" target="_blank" rel="noopener">Padrón oficial</a> · <a href="/data/conduction.json" download>Conciliación de ministros y secretarios</a> · <a href="/data/salary-hierarchy.json" download>Conteos y referencias salariales</a></p></details></section>`}
document.addEventListener('click',e=>{const b=e.target.closest('[data-conduction-list]');if(!b)return;document.getElementById('conduction-lists').open=true;const target=document.getElementById('conduction-'+b.dataset.conductionList);target.focus({preventScroll:true});target.scrollIntoView({block:'start',behavior:'smooth'})});

function annualTick(i,length,width,year){if(i===0||i===length-1||length<=5)return true;const step=width>=950?2:width>=600?3:5;return i%step===0&&i<length-2;}


function vizTip(lines){return `data-viz-tip="${E(JSON.stringify(lines))}"`;}
let vizTooltip=null,vizOwner=null;
function hideVizTip(){if(!vizTooltip)return;vizTooltip.classList.remove('visible');vizTooltip.setAttribute('aria-hidden','true');vizOwner?.removeAttribute('aria-describedby');vizOwner=null;}
function showVizTip(el){
 if(!el?.dataset.vizTip)return;if(!vizTooltip){vizTooltip=document.createElement('div');vizTooltip.id='viz-tooltip';vizTooltip.className='viz-tooltip';vizTooltip.setAttribute('role','tooltip');document.body.append(vizTooltip);}
 const lines=JSON.parse(el.dataset.vizTip);vizTooltip.innerHTML=lines.slice(0,4).map((t,i)=>`<${i?'span':'strong'}>${E(t)}</${i?'span':'strong'}>`).join('');vizOwner?.removeAttribute('aria-describedby');vizOwner=el;el.setAttribute('aria-describedby','viz-tooltip');vizTooltip.setAttribute('aria-hidden','false');
 const r=el.getBoundingClientRect();vizTooltip.style.left='0px';vizTooltip.style.top='0px';const w=vizTooltip.offsetWidth,h=vizTooltip.offsetHeight;vizTooltip.style.left=Math.max(8,Math.min(innerWidth-w-8,r.left+r.width/2-w/2))+'px';vizTooltip.style.top=Math.max(8,r.top-h-10>8?r.top-h-10:Math.min(innerHeight-h-8,r.bottom+10))+'px';vizTooltip.classList.add('visible');
}
document.addEventListener('pointerover',e=>{if(e.pointerType==='touch')return;const el=e.target.closest('[data-viz-tip]');if(el)showVizTip(el);});
document.addEventListener('pointerout',e=>{if(vizOwner&&!vizOwner.contains(e.relatedTarget))hideVizTip();});
document.addEventListener('focusin',e=>{const el=e.target.closest('[data-viz-tip]');if(el)showVizTip(el);else hideVizTip();});
document.addEventListener('focusout',e=>{if(vizOwner===e.target)hideVizTip();});
document.addEventListener('click',e=>{const el=e.target.closest('[data-viz-tip]');if(el)showVizTip(el);else hideVizTip();});
document.addEventListener('keydown',e=>{if(e.key==='Escape')hideVizTip();if((e.key==='Enter'||e.key===' ')&&e.target.matches('svg [role="button"]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
addEventListener('scroll',hideVizTip,{passive:true});addEventListener('resize',hideVizTip);
const revealedViews=new Set();
function enhanceVisuals(view){
 hideVizTip();const content=document.getElementById('content');
 for(const el of content.querySelectorAll('[data-treemap-info]')){el.dataset.vizTip=JSON.stringify(el.dataset.treemapInfo.split(': ').slice(0,2));el.removeAttribute('title');}
 for(const el of content.querySelectorAll('.trend-svg circle')){const title=el.querySelector('title');if(title){el.dataset.vizTip=JSON.stringify([title.textContent]);el.setAttribute('tabindex','0');el.setAttribute('role','button');el.setAttribute('aria-label',title.textContent);title.remove();}}
 if(view==='compare'&&state.compareUniverse!=='world'){const c=comparisonState();for(const el of content.querySelectorAll('[data-province]')){const row=c.p.rows.find(r=>r.id===el.dataset.province);if(!row)continue;const rank=c.rows.findIndex(r=>r.id===row.id)+1;el.dataset.vizTip=JSON.stringify([row.name,comparisonValue(row.indicators[c.ind.id],c.ind),rank?`Posición ${rank} de ${c.rows.length}`:'Sin dato']);el.querySelector('title')?.remove();}}
 for(const el of content.querySelectorAll('.world-row'))el.dataset.vizTip=JSON.stringify([el.querySelector('.world-name b').textContent,el.querySelector('strong').textContent,el.querySelector('.world-name small').textContent]);
 for(const el of content.querySelectorAll('.waterfall-row')){el.tabIndex=0;el.dataset.vizTip=JSON.stringify([el.firstElementChild.textContent,el.lastElementChild.textContent,'Cuenta ahorro–inversión · pesos nominales']);}
 // Exact amounts remain downloadable; long primary tables start collapsed.
 for(const el of content.querySelectorAll('.table-wrap'))if(!el.closest('details')&&!['method'].includes(view)&&el.querySelectorAll('tbody tr').length>7){const d=document.createElement('details');d.className='exact-values';d.innerHTML='<summary>Ver tabla completa</summary>';el.replaceWith(d);d.append(el);}
 const key=view==='project'?view+'-'+state.projectTab:view;if(revealedViews.has(key)||matchMedia('(prefers-reduced-motion: reduce)').matches)return;revealedViews.add(key);
 const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target);}},{threshold:.05});for(const el of content.querySelectorAll('.home-section,.chart-panel,.project-kpis')){el.classList.add('reveal');observer.observe(el);}setTimeout(()=>observer.disconnect(),15000);
}
