'use strict';
// A proposal has its own route and schema; it never becomes an execution period.
routeNames.project='proyecto-2027';
const projectTabs={summary:'Resumen',expenses:'Gastos',revenue:'Ingresos',compare:'Comparar con 2026'};
const projectDimensions={purposes:'Finalidad',functions:'Finalidad y función',jurisdictions:'Jurisdicción',objects:'Objeto del gasto',economic:'Gastos corrientes y de capital'};
const methodSections={'presupuesto-2027':'Proyecto de Presupuesto 2027','presupuesto-2026':'Presupuesto 2026',ejecucion:'Ejecución',ingresos:'Ingresos',caif:'Resultados fiscales · CAIF',historia:'Historia',provincias:'Provincias',mundo:'Ciudades del mundo',funcionarios:'Funcionarios',sueldos:'Sueldos'};
const projectMetricLabels={currentExpense:'Gastos corrientes',capitalExpense:'Gastos de capital',fiscalExpense:'Gasto fiscal solicitado',legalHeadline:'Total del artículo 1',currentRevenue:'Ingresos corrientes',capitalRevenue:'Recursos de capital',fiscalRevenue:'Recursos estimados',economicPrimaryResult:'Resultado económico primario',economicResult:'Resultado económico, con intereses',primaryExpense:'Gasto primario',primaryResult:'Resultado primario',interest:'Intereses de la deuda',financialResult:'Resultado financiero',figurativeExpense:'Gastos figurativos',figurativeRevenue:'Contribuciones figurativas',financialSources:'Fuentes financieras',financialApplications:'Aplicaciones financieras',debtAmortizationAndOtherLiabilities:'Amortización de deuda y disminución de otros pasivos',debtAndOtherLiabilities:'Endeudamiento e incremento de otros pasivos',financialInvestmentIncrease:'Incremento de inversión financiera',financialInvestmentDecrease:'Disminución de inversión financiera',perCapita:'Gasto solicitado por habitante'};
const detailLink=(section='presupuesto-2027',label='Más detalle')=>`<a class="text-link" href="#metodologia?seccion=${section}" data-method-section="${section}">${label} ↗</a>`;
const budgetCondition=()=>state.config.featuredBudgetStatus==='project'?'Proyecto':'Presupuesto aprobado';
const projectTitle=()=>state.config.featuredBudgetStatus==='project'?'Proyecto de Presupuesto '+state.config.featuredBudgetYear:'Presupuesto '+state.config.featuredBudgetYear;
const projectButton=(tab,label,dimension='')=>`<button class="text-link" data-project-tab="${tab}" ${dimension?`data-project-dimension="${dimension}"`:''}>${label} ↗</button>`;
function projectKpi(key,label){const m=state.project.summary[key];return `<article><span>${label}</span><strong>${money(m.value)}</strong>${key==='perCapita'?'<small>Censo 2022 · 3.121.707 habitantes</small>':''}${detailLink()}</article>`;}
function projectLanding(){
 const H=state.content.home,p=state.project,s=p.summary,c=state.currentBudget;
 const questions=H.questions.items.map(([n,t,desc,,visual],i)=>{const tab=['expenses','revenue','expenses','compare'][i],dim=i===2?'objects':'';return `<button class="question-card" data-project-tab="${tab}" ${dim?`data-project-dimension="${dim}"`:''}><span class="question-number">${n} <span aria-hidden="true">↗</span></span><h3>${E(t)}</h3><p>${E(desc)}</p><span class="mini-visual ${visual}" aria-hidden="true">${visual==='line'?'<svg viewBox="0 0 220 50"><path d="M0 44 L35 31 L72 37 L107 15 L140 22 L180 9 L220 2"/></svg>':'<i></i><i></i><i></i><i></i>'}</span></button>`;}).join('');
 return `<div class="citizen-home"><section class="intro"><div><p class="eyebrow">${E(H.hero.eyebrow)}</p><h1>${E(H.hero.title)}<span>.</span></h1><p class="intro-copy">${E(H.hero.description)}</p><button class="primary-btn" data-project-tab="summary">${E(H.hero.action)} ↗</button></div><aside class="intro-aside"><span class="city-rule"></span><p>${H.hero.aside}</p><small>${H.hero.source}</small></aside></section>
 <section class="home-section panorama" aria-labelledby="panorama-title"><p class="eyebrow">${E(H.panorama.eyebrow)}</p><h2 id="panorama-title">${E(H.panorama.title)}</h2><div class="panorama-grid">
 <article><p>Presupuesto 2026 — vigente al 30/06/2026</p><strong>${money(c.budget)}</strong><span>${E(H.panorama.budgetDescription)}</span>${provenance('official',H.panorama.budgetNote)}<button class="text-link" data-view="home" data-snapshot="2026-2">Ver el presupuesto 2026 ↗</button></article>
 <article><p>${E(H.panorama.projectLabel)} <span class="project-badge">${budgetCondition()}</span></p><strong>${money(s.fiscalExpense.value)}</strong><span>${E(H.panorama.projectDescription)}</span><details class="provenance official"><summary>DATO OFICIAL ⓘ</summary><p>≈ $${fmt(s.fiscalExpense.value/1e12,1)} billones. ${E(s.fiscalExpense.reference)} · página ${s.fiscalExpense.pdfPage} del PDF. Gastos corrientes y de capital; figurativas y aplicaciones financieras separadas.</p>${detailLink()}</details>${projectButton('summary','Explorar Proyecto 2027')}</article>
 <article><p>${E(H.panorama.projectPerCapitaLabel)}</p><strong>${money(s.perCapita.value)}</strong><span>${E(H.panorama.projectPerCapitaDescription)}</span><details class="provenance calculation"><summary>CÁLCULO PROPIO ⓘ</summary><p>${E(s.perCapita.method)}</p>${detailLink()}</details>${projectButton('compare','Comparar con 2026')}</article></div></section>
 ${homeFiscalReadings()}<section class="home-section"><h2>${E(H.questions.title)}</h2><div class="question-grid">${questions}</div></section>
 <section class="comparison-cta"><div><p class="eyebrow">${E(H.comparison.eyebrow)}</p><h2>${E(H.comparison.title)}</h2><p>${E(H.comparison.description)}</p></div><button class="primary-btn" data-view="compare">Comparar CABA ↗</button></section>
 <section class="reading-guide"><h2>${E(H.guide.title)}</h2><p>${E(H.guide.description)}</p><button class="text-link" data-view="explained">Entender el presupuesto en pocos minutos ↗</button></section></div>`;
}
function projectTable(rows,total,showShare=true){return `<div class="table-wrap"><table class="project-values"><caption>Proyecto 2027 · pesos nominales · ${rows.length} categorías</caption><thead><tr><th>Categoría</th><th>Importe solicitado</th>${showShare?'<th>Participación</th>':''}<th>Detalle</th></tr></thead><tbody>${rows.map(r=>`<tr><th scope="row">${E(r.name)}${r.purpose?`<small class="office">${E(r.purpose)}</small>`:''}</th><td class="num">${money(r.value)}</td>${showShare?`<td class="num">${pct(r.value/total*100)}</td>`:''}<td>${r.dimension==='purposes'?`<button class="text-link" data-project-purpose="${E(r.name)}">Ver funciones ↗</button>`:detailLink()}</td></tr>`).join('')}</tbody></table></div>`;}
function projectSummary(){const s=state.project.summary;return `<div class="project-kpis">${projectKpi('fiscalExpense','Gasto fiscal solicitado')}${projectKpi('fiscalRevenue','Recursos estimados')}${projectKpi('financialResult','Superávit financiero proyectado')}${projectKpi('perCapita','Por porteño, por año')}</div><section class="chart-panel"><h2>¿A qué se destina el gasto solicitado?</h2>${compositionTreemap(state.project.breakdowns.purposes.map(r=>({...r,action:`data-project-purpose="${E(r.name)}"`})),{label:'Gasto por finalidad · Proyecto 2027'})}${projectButton('expenses','Explorar gastos')}${detailLink()}</section><section class="project-income-brief"><h2>Los ingresos estimados</h2><p>Los recursos corrientes suman ${money(s.currentRevenue.value)} y los de capital, ${money(s.capitalRevenue.value)}.</p>${projectButton('revenue','Explorar ingresos')}</section>`;}
function projectExpenses(){
 const key=projectDimensions[state.projectDimension]?state.projectDimension:'purposes',selected=state.projectPurpose;
 let rows=state.project.breakdowns[key].map(r=>({...r,dimension:key})),total=state.project.summary.fiscalExpense.value;
 if(selected){rows=state.project.breakdowns.functions.filter(r=>r.purpose===selected);total=rows.reduce((v,r)=>v+r.value,0);}
 rows=rows.slice().sort((a,b)=>b.value-a.value);
 return `<div class="tools project-controls"><label>Mirar por<select id="project-dimension">${Object.entries(projectDimensions).map(([k,name])=>`<option value="${k}" ${k===key?'selected':''}>${name}</option>`).join('')}</select></label>${selected?`<button class="small-btn" data-project-reset>Volver al total</button>`:''}</div><h2>${selected?E(selected):'Cómo se distribuye el gasto solicitado'}</h2><p class="chart-unit">${selected?'Funciones de esta finalidad':'Gastos corrientes y de capital'} · ${money(total)} · pesos nominales de 2027</p>${compositionTreemap(rows.map(r=>({...r,action:key==='purposes'&&!selected?`data-project-purpose="${E(r.name)}"`:''})),{label:selected?'Funciones de '+selected:'Gasto por '+projectDimensions[key].toLowerCase()})}${projectTable(rows,total)}${detailLink()}<details class="project-financing"><summary>Operaciones separadas del gasto fiscal</summary><p>Las figurativas y las aplicaciones financieras no integran los ${money(state.project.summary.fiscalExpense.value)} del gasto solicitado.</p>${projectTable(['figurativeExpense','financialApplications','debtAmortizationAndOtherLiabilities'].map(k=>({name:projectMetricLabels[k],...state.project.summary[k]})),state.project.summary.fiscalExpense.value,false)}<p>Son magnitudes separadas y no una composición que se deba sumar al gasto fiscal.</p>${detailLink()}</details>`;
}
function projectRevenue(){const key=state.projectRevenueMode==='taxRevenue'?'taxRevenue':'revenue',rows=state.project.breakdowns[key],total=rows.reduce((v,r)=>v+r.value,0);return `<div class="tools"><label>Apertura<select id="project-revenue-mode"><option value="revenue">Todos los recursos</option><option value="taxRevenue" ${key==='taxRevenue'?'selected':''}>Ingresos tributarios estimados</option></select></label></div><h2>¿De dónde vendrían los recursos?</h2><p class="chart-unit">Recursos estimados · pesos nominales de 2027${key==='taxRevenue'?' · composición de los ingresos tributarios':''}</p>${compositionTreemap(rows,{label:key==='taxRevenue'?'Ingresos tributarios estimados':'Composición de los recursos estimados'})}${projectTable(rows,total)}${detailLink()}<p class="note">Son estimaciones de recaudación del proyecto; no describen cambios en las normas tributarias.</p>`;}
function projectCompare(){
 const d=state.projectComparison;if(!d)return '<p>No hay una comparación conciliada disponible.</p>';
 const real=state.projectPrices!=='nominal',key=state.projectCompareDimension==='objects'?'objects':'purposes',rows=d.groups[key],value=real?d.totals.projectAdjusted:d.totals.project,max=Math.max(d.totals.reference,value),rate=real?d.totals.realVariationPct:d.totals.nominalVariationPct;
 return `<h2>Dos autorizaciones anuales</h2><div class="tools"><label>Mirar los importes<select id="project-compare-prices"><option value="real" ${real?'selected':''}>Ajustados por inflación proyectada</option><option value="nominal" ${!real?'selected':''}>Nominales</option></select></label></div><p class="chart-unit">2026: presupuesto actualizado al 30/06 · 2027: proyecto · ${real?'montos 2027 divididos por 1,18, como aproximación a precios de 2026':'pesos nominales de cada año'}.</p><p class="project-comparison-result">${real?'Variación real estimada':'Variación nominal'} del gasto total: <strong>${signedPct(rate)}</strong></p><p class="note">Inflación proyectada IPC diciembre/diciembre 2027: <b>18,0%</b>. Es un supuesto para comparar presupuestos anuales.</p><div class="project-budget-bars" role="img" aria-label="Autorizaciones anuales · ${real?'ajuste proyectado con IPC de 18%':'importes nominales'}">${[['2026 al 30/06',d.totals.reference],[real?'Proyecto 2027 · ajustado':'Proyecto 2027',value]].map(([n,v],i)=>`<div><span>${n}</span><i><b style="width:${v/max*100}%;background:${i?'#67339b':'#8f7aa0'}"></b></i><strong>${money(v)}</strong></div>`).join('')}</div><div class="tools"><label>Comparar por<select id="project-compare-dimension"><option value="purposes">Finalidad</option><option value="objects" ${key==='objects'?'selected':''}>Objeto del gasto</option></select></label></div><div class="table-wrap"><table><caption>Mismo universo fiscal · ${real?'variación real estimada con IPC proyectado de 18,0%':'comparación nominal'}</caption><thead><tr><th>Categoría</th><th>2026 actualizado al 30/06</th><th>${real?'Proyecto 2027 · ajustado':'Proyecto 2027 · nominal'}</th><th>${real?'Variación real estimada':'Variación nominal'}</th></tr></thead><tbody>${rows.map(r=>{const pctValue=real?r.realVariationPct:r.nominalVariationPct;return `<tr><th scope="row">${E(r.name)}</th><td class="num">${money(r.reference)}</td><td class="num">${money(real?r.projectAdjusted:r.project)}</td><td class="num">${pctValue===null?'Sin base':signedPct(pctValue)}</td></tr>`;}).join('')}</tbody></table></div>${detailLink()}<p class="note">La referencia 2026 puede cambiar durante el año. El proyecto 2027 todavía requiere aprobación legislativa.</p>`;
}
function projectDisplayUnit(){return state.projectTab==='compare'?state.projectPrices==='nominal'?'Pesos nominales de cada año':'Ajuste con inflación proyectada · IPC 18,0%':'Pesos nominales de '+state.config.featuredBudgetYear;}
function projectComparisonMethod(){const d=state.projectComparison;if(!d?.deflator)return '';return `<p>2026 / 2027: se comparan autorizaciones anuales, ambas antes de figurativas y financiamiento. Los objetos se concilian por código de inciso y las finalidades por denominación. La vista real divide el monto 2027 por <b>1,18</b>; la vista nominal conserva los importes publicados.</p><p><b>Deflactor elegido:</b> IPC diciembre/diciembre 2027, <b>18,0%</b>, proyección indicada por el usuario el 01/10/2026. Se registra como valor aportado, sin asignarle una página del PDF no verificada. ${E(d.deflator.limitation)}</p><p><b>Fórmula:</b> ${E(d.deflator.formula)}. La variación real es estimada y depende del supuesto; no mide gasto ejecutado.</p>`;}

extraViews.project=()=>`<section class="panel project-page"><p class="eyebrow">${budgetCondition().toUpperCase()} · ${state.config.featuredBudgetYear}</p><h1>${projectTitle()}</h1><p class="chart-unit">${state.config.featuredBudgetStatus==='project'?'Propuesta del Poder Ejecutivo · pendiente de aprobación legislativa':'Autorización presupuestaria'} · ${projectDisplayUnit()}</p>${({summary:projectSummary,expenses:projectExpenses,revenue:projectRevenue,compare:projectCompare}[state.projectTab]||projectSummary)()}</section>`;
function salaryLatestPanel(){const d=state.salaryReference;if(!d)return '';return `<section class="salary-latest"><p class="eyebrow">JORGE MACRI · JEFE DE GOBIERNO</p><h2>Último salario bruto publicado</h2><strong>${money(d.latest.value)}</strong><span>${state.salaries.months[d.latest.month-1]} ${d.latest.year} · bruto mensual sin aguinaldo</span><p>Equivale a <b>${fmt(d.ratio,2)} veces</b> el sueldo bruto mensual del Presidente de la Nación.</p><details><summary>Fuente y alcance ↗</summary><p>${E(d.method)}</p><p><a href="${E(d.latest.source)}" target="_blank" rel="noopener">Registro oficial del GCBA</a> · último mes disponible verificado: julio de 2026. Referencia presidencial: ${money(d.president.value)}, <a href="${E(d.president.source)}" target="_blank" rel="noopener">Informe 142, pregunta 938, páginas 726–727</a>. <a href="${E(d.president.freezeSource)}" target="_blank" rel="noopener">Decreto 931/2025, artículos 2 y 3</a>.</p><a href="/data/salary-latest-reference.json" download>Datos y cálculo</a> · <a href="/data/salary-jorge-macri.csv" download>Serie histórica conservada</a></details></section>`;}

const executionTabs=document.querySelector('.tabs').innerHTML,baseExplorerShell=explorerShell;
explorerShell=function(){document.querySelector('.tabs').innerHTML=executionTabs;baseExplorerShell();if(!state.config.featuredBudgetFile)return;const project=state.view==='project';if(project){document.querySelectorAll('#period-tabs .active').forEach(b=>b.classList.remove('active'));document.querySelector('.tabs').innerHTML=state.config.projectViews.filter(k=>k!=='compare'||state.config.projectComparisonFile).map(k=>`<button data-project-tab="${k}" aria-pressed="${(state.projectTab||'summary')===k}" class="${(state.projectTab||'summary')===k?'active':''}">${projectTabs[k]}</button>`).join('');document.querySelector('.price-label').textContent=budgetCondition()+' · '+projectDisplayUnit();document.querySelector('.search-label').hidden=document.querySelector('.search-box').hidden=true;}document.querySelector('#period-tabs').insertAdjacentHTML('afterbegin',`<button data-project-tab="summary" class="${project?'active':''}">${E(state.config.featuredBudgetLabel)}</button>`);document.querySelector('#updated-label').textContent+=' · Proyecto 2027: documento del 30/09/2026';};
const baseReadRoute=readRoute,baseSyncRoute=syncRoute;
readRoute=function(){baseReadRoute();const q=new URLSearchParams(location.hash.split('?')[1]||'');if(state.view==='project'){state.projectTab=state.config.projectViews.includes(q.get('vista'))?q.get('vista'):'summary';state.projectDimension=projectDimensions[q.get('apertura')]?q.get('apertura'):'purposes';state.projectPurpose=null;const purpose=q.get('finalidad');if(purpose&&purpose.length<100)state.projectPurpose=purpose;}if(state.view==='project'){state.projectRevenueMode=q.get('apertura')==='taxRevenue'?'taxRevenue':'revenue';state.projectCompareDimension=q.get('apertura')==='objects'?'objects':'purposes';state.projectPrices=q.get('precios')==='nominal'?'nominal':'real';}state.methodSection=state.view==='method'&&methodSections[q.get('seccion')]?q.get('seccion'):null;};
syncRoute=function(){if(state.view==='project'){const q=new URLSearchParams({vista:state.projectTab||'summary'});if(state.projectTab==='expenses'){q.set('apertura',state.projectDimension||'purposes');if(state.projectPurpose)q.set('finalidad',state.projectPurpose);}if(state.projectTab==='revenue')q.set('apertura',state.projectRevenueMode||'revenue');if(state.projectTab==='compare'){q.set('apertura',state.projectCompareDimension||'purposes');q.set('precios',state.projectPrices||'real');}const hash='#proyecto-2027?'+q;if(location.hash!==hash)window.history.pushState(null,'',hash);}else if(state.view==='method'&&state.methodSection){const hash='#metodologia?seccion='+state.methodSection;if(location.hash!==hash)history.pushState(null,'',hash);}else baseSyncRoute();if(state.view==='method'&&state.methodSection)setTimeout(()=>document.getElementById('metodo-'+state.methodSection)?.scrollIntoView({block:'start',behavior:'instant'}),0);};
document.addEventListener('click',e=>{
 const method=e.target.closest('[data-method-section]');if(method){e.preventDefault();e.stopImmediatePropagation();state.view='method';state.methodSection=method.dataset.methodSection;state.navigationRequested=false;render();return;}
 const project=e.target.closest('[data-project-tab],[data-project-purpose],[data-project-reset]'),mainExplore=e.target.closest('.main-nav [data-view="summary"]'),period=e.target.closest('[data-period]');
 if(period&&state.view==='project'){e.preventDefault();e.stopImmediatePropagation();state.period=period.dataset.period;state.view='summary';state.navigationRequested=true;render();return;}
 if(!project&&!mainExplore)return;e.preventDefault();e.stopImmediatePropagation();state.view='project';state.projectTab=project?.dataset.projectTab||'summary';state.projectPurpose=project?.dataset.projectPurpose||null;if(state.projectPurpose)state.projectTab='expenses';if(project?.dataset.projectDimension)state.projectDimension=project.dataset.projectDimension;if(project?.hasAttribute('data-project-reset')){state.projectPurpose=null;state.projectTab='expenses';}state.navigationRequested=true;render();
},true);
document.addEventListener('change',e=>{const keys={'project-dimension':'projectDimension','project-revenue-mode':'projectRevenueMode','project-compare-dimension':'projectCompareDimension','project-compare-prices':'projectPrices'};if(keys[e.target.id]){state[keys[e.target.id]]=e.target.value;state.projectPurpose=null;render();}});

function projectMethod(){const p=state.project;if(!p)return '';return `<p><b>Fuente primaria:</b> ${E(p.source.document)} · ${E(p.source.documentId)} · 30/09/2026. El PDF aportado no se copia al repositorio público. Las páginas indicadas son las físicas del PDF de 297 páginas, no la numeración interna de cada anexo.</p><p>${E(p.universe)} El total del artículo 1 coincide con el gasto fiscal comparable: no se depura un agregado mayor para construir la portada.</p><div class="table-wrap"><table><thead><tr><th>Variable</th><th>Valor</th><th>Página PDF</th><th>Referencia</th></tr></thead><tbody>${Object.entries(p.summary).map(([key,r])=>`<tr><th scope="row">${projectMetricLabels[key]}</th><td class="num">${money(r.value)}</td><td>${r.pdfPage}</td><td>${E(r.reference)}${r.method?`<p>${E(r.method)}</p>`:''}</td></tr>`).join('')}</tbody></table></div><p>La CAIF identifica resultado económico <b>primario</b> antes de intereses. El resultado económico que incluye intereses se calcula por separado. El inciso de servicio de deuda incluye intereses y comisiones; no equivale a la línea de intereses de la CAIF.</p>${projectComparisonMethod()}<h3>Aperturas y referencias</h3><ul>${Object.entries(p.breakdowns).map(([key,rows])=>`<li>${E(projectDimensions[key]||({revenue:'Recursos',taxRevenue:'Ingresos tributarios'}[key]))}: ${rows.length} categorías · ${E(rows[0].reference)} · página ${rows[0].pdfPage}.</li>`).join('')}</ul><h3>Autorizaciones del propio presupuesto</h3>${projectTable(p.creditAuthorizations,p.summary.fiscalExpense.value,false)}<p>La Planilla 43 muestra cuatro montos individualizados y letras de Tesorería sin monto numérico en esa fila. No se agrega deuda de proyectos externos ni se suman estas autorizaciones nuevamente a los gastos. Se conserva el artículo 11 como referencia del alcance de las facultades.</p><h3>Supuestos y límites</h3><p>${E(p.macroAssumptions.qualitative)} Páginas 31–32.</p><ul>${p.limitations.map(t=>`<li>${E(t)}</li>`).join('')}</ul><p><a href="${Site.url('data/budget/2027/project.json')}" download>Proyecto: datos y trazabilidad JSON</a> · <a href="${Site.url('data/budget/2027/project.csv')}" download>Clasificaciones CSV</a> · <a href="${Site.url('data/budget/2027/comparison-2026.json')}" download>Comparación conciliada y deflactor</a></p>`;}
function methodPage(html){const t=document.createElement('template');t.innerHTML=html;const panel=t.content.querySelector('.panel');if(!panel)return html;const groups=Object.fromEntries(Object.keys(methodSections).map(k=>[k,[]]));for(const d of panel.querySelectorAll(':scope > details')){const title=d.querySelector('summary')?.textContent||'';let k=/sueldo|salar/i.test(title)?'sueldos':/mundo|ciudad|internacional/i.test(title)?'mundo':/provinc|comparaci[oó]n.*nacional/i.test(title)?'provincias':/ingreso|recurso/i.test(title)?'ingresos':/resultado|fiscal 2025|CAIF|semestre/i.test(title)?'caif':/histor|inflaci[oó]n|precio|USD|REM/i.test(title)?'historia':/gobierno|jer[aá]rqui|funcionario|organigrama/i.test(title)?'funcionarios':/presupuesto|universo/i.test(title)?'presupuesto-2026':'ejecucion';d.removeAttribute('open');groups[k].push(d.outerHTML);d.remove();}
 const nav=`<nav class="method-index" aria-label="Índice de fuentes y metodología">${Object.entries(methodSections).map(([id,label])=>detailLink(id,label)).join('')}</nav>`;
 panel.insertAdjacentHTML('beforeend',nav+Object.entries(methodSections).map(([id,label])=>`<section class="method-section" id="metodo-${id}" tabindex="-1"><h2>${label}</h2>${id==='presupuesto-2027'?projectMethod():id==='provincias'?justiceNote(true):''}${groups[id].join('')}${groups[id].length||id==='presupuesto-2027'?'':`<p>Los valores, las fuentes y la cobertura de este dominio se conservan en los datos descargables de cada vista.</p>${sourceDownloadsFor(id)}`}</section>`).join(''));return t.innerHTML;}
function sourceDownloadsFor(section){const ids={ingresos:['income-2026-2','income-2025-4'],provincias:['comparisons-argentina'],mundo:['comparisons-world'],funcionarios:['government-directory','conduction'],sueldos:['salary-latest-reference','salaries']}[section]||[];return ids.map(id=>`<p><a href="${Site.url('data/'+id+'.json')}" download>Datos y fuentes · ${section}</a></p>`).join('');}
function polishMarkup(html,view){
 if(view==='method')return methodPage(html);const t=document.createElement('template');t.innerHTML=html;
 if(view==='compare'&&state.compareUniverse!=='world'){
  const layout=t.content.querySelector('.national-layout'),controls=t.content.querySelector('.compare-controls');if(layout&&controls){const notes=[];for(let n=controls.nextElementSibling;n&&n!==layout;){const next=n.nextElementSibling;if(!n.classList.contains('chart-unit'))notes.push(n);n=next;}if(notes.length){const details=document.createElement('details');details.className='comparison-method';details.innerHTML='<summary>Más detalle · alcance y metodología</summary>';for(const n of notes)details.append(n);layout.after(details);}
   const context=document.createElement('p');context.className='chart-unit';context.innerHTML=(comparisonState().p.kind==='budget'?'CABA actualizado al 30/06/2026; otras provincias aprobado o prorrogado. ':'')+'Población Censo 2022. '+detailLink('provincias');controls.after(context);
   if(t.content.querySelector('.justice-note')){const method=t.content.querySelector('.comparison-method');if(method)for(const full of t.content.querySelectorAll('.justice-note'))method.append(full);const note=document.createElement('p');note.className='justice-compact';note.innerHTML='Las competencias judiciales no son idénticas entre CABA y las provincias. '+detailLink('provincias');layout.before(note);}
  }
 }
 if(!['landing','project','explained'].includes(view))for(const p of t.content.querySelectorAll('.chart-panel > p.note,.semester-analysis > p.note,.income-comparison > p.note,.notice')){
  if(p.closest('details')||p.textContent.length<210)continue;
  const d=document.createElement('details');d.className='method-on-demand';d.innerHTML='<summary>Más detalle · cobertura y cálculo</summary>';p.replaceWith(d);d.append(p);
 }
 return t.innerHTML;
}
